SLOTH: AnalyticalIdealSolution< T > Class Template Reference
AnalyticalIdealSolution< T > Class Template Reference
#include <AnalyticalIdealSolution.hpp>
Public Member Functions
constexpr AnalyticalIdealSolution (const Parameters &params)
Construct a new AnalyticalIdealSolution::AnalyticalIdealSolution object.
constexpr AnalyticalIdealSolution (const Parameters &params, bool is_KKS)
Construct a new AnalyticalIdealSolution::AnalyticalIdealSolution object.
void execute (const int dt, const std::set< int > &list_nodes, const std::vector< T > &aux_gf, const std::vector< std::tuple< std::string, std::string >> &chemical_system, std::optional< std::vector< std::tuple< std::string, std::string, double >>> status_phase=std::nullopt) override
Main method to calculate equilibrium states.
void finalize () override
Finalization actions (free memory)
void get_parameters () override
Get the parameters associated with the AnalyticalIdealSolution object.
void initialize (const std::vector< std::tuple< std::string, std::string >> &sorted_chemical_system) override
Initialization of the thermodynamic calculation.
~AnalyticalIdealSolution ()
Destroy the Binary Melting< T>:: Binary Melting object.
Public Member Functions inherited from CalphadBase< T >
CalphadBase (const Parameters &params)
Construct a new CalphadBase object.
CalphadBase (const Parameters &params, bool is_KKS)
Construct a new CalphadBase object.
const std::multimap< IterationKey, SpecializedValue > get_time_specialized () const
Return values calculated at a given iteration.
void global_execute (const int dt, const double time_step, const std::vector< T > &tp_gf, const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< T >>> &output_system, const std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> &previous_output_system, std::optional< const std::tuple< std::string, T, T >> phase_fields=std::nullopt, std::optional< const std::vector< T >> tp_gf_old=std::nullopt, std::optional< const std::vector< std::tuple< std::string, std::string, T, T >>> x_gf=std::nullopt, std::optional< const std::vector< std::tuple< std::string, T >>> coordinates=std::nullopt)
High-level method for managing equilibrium calculations.
virtual ~CalphadBase ()
Destroy the Calphad Base< T>:: Calphad Base object.
Additional Inherited Members
Public Attributes inherited from CalphadBase< T >
std::map< std::tuple< int, std::string >, double > chemical_potentials_
std::map< std::tuple< int, std::string >, double > diffusion_chemical_potentials_
std::map< std::tuple< int, std::string >, double > driving_forces_
std::map< std::tuple< int, std::string, std::string >, double > elem_mole_fraction_by_phase_
std::string element_removed_from_ic_
std::map< std::tuple< int, std::string, std::string >, double > energies_of_phases_
std::map< int, int > error_equilibrium_
std::map< std::tuple< int, std::string >, double > mole_fraction_of_phase_
std::map< std::tuple< int, std::string >, double > nucleus_
const Parameters & params_
std::multimap< IterationKey, SpecializedValue > time_specialized_
Time integral results.
Protected Member Functions inherited from CalphadBase< T >
void clear_containers ()
Clear containers used to store the results of equilibrium calculations.
void update_outputs (const int dt, const size_t nb_nodes, std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< T >>> &output_system, const std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> &previous_output_system)
Update the outputs on the basis of results stored in containers.
Protected Attributes inherited from CalphadBase< T >
std::shared_ptr< CalphadUtils< T > > CU_
std::map< int, double > heat_capacity_
std::shared_ptr< KKS< T > > KKS_
std::map< std::tuple< int, std::string, std::string >, double > mobilities_
std::map< std::tuple< int, std::string, std::string, int >, double > site_fraction_
Detailed Description
template<typename T>
class AnalyticalIdealSolution< T >
Definition at line 44 of file AnalyticalIdealSolution.hpp.
Constructor & Destructor Documentation
AnalyticalIdealSolution() [1/2]
template<typename T > constexpr AnalyticalIdealSolution< T >::AnalyticalIdealSolution (const Parameters & params) explicit constexpr
Construct a new AnalyticalIdealSolution::AnalyticalIdealSolution object.
Parameters
params
Definition at line 97 of file AnalyticalIdealSolution.hpp.
References AnalyticalIdealSolution< T >::get_parameters().
AnalyticalIdealSolution() [2/2]
template<typename T > constexpr AnalyticalIdealSolution< T >::AnalyticalIdealSolution (const Parameters & params, bool is_KKS) constexpr
Construct a new AnalyticalIdealSolution::AnalyticalIdealSolution object.
Parameters
params
is_KKS
Definition at line 110 of file AnalyticalIdealSolution.hpp.
References AnalyticalIdealSolution< T >::get_parameters().
~AnalyticalIdealSolution()
template<typename T > AnalyticalIdealSolution< T >::~AnalyticalIdealSolution
Destroy the Binary Melting< T>:: Binary Melting object.
Template Parameters
T
Definition at line 265 of file AnalyticalIdealSolution.hpp.
Member Function Documentation
execute()
template<typename T > void AnalyticalIdealSolution< T >::execute (const int dt, const std::set< int > & list_nodes, const std::vector< T > & tp_gf, const std::vector< std::tuple< std::string, std::string >> & chemical_system, std::optional< std::vector< std::tuple< std::string, std::string, double >>> status_phase = std::nullopt) override virtual
Main method to calculate equilibrium states.
Template Parameters
T
Parameters
dt
aux_gf
chemical_system
output_system
Implements CalphadBase< T >.
Definition at line 135 of file AnalyticalIdealSolution.hpp.
finalize()
template<typename T > void AnalyticalIdealSolution< T >::finalize override virtual
Finalization actions (free memory)
Template Parameters
T
Implements CalphadBase< T >.
Definition at line 257 of file AnalyticalIdealSolution.hpp.
get_parameters()
template<typename T > void AnalyticalIdealSolution< T >::get_parameters override virtual
Get the parameters associated with the AnalyticalIdealSolution object.
Template Parameters
T
Reimplemented from CalphadBase< T >.
Definition at line 85 of file AnalyticalIdealSolution.hpp.
References CalphadBase< T >::get_parameters().
Referenced by AnalyticalIdealSolution< T >::AnalyticalIdealSolution().
initialize()
template<typename T > void AnalyticalIdealSolution< T >::initialize (const std::vector< std::tuple< std::string, std::string >> & sorted_chemical_system) override virtual
Initialization of the thermodynamic calculation.
Template Parameters
T
Implements CalphadBase< T >.
Definition at line 122 of file AnalyticalIdealSolution.hpp.
The documentation for this class was generated from the following file:
AnalyticalIdealSolution.hpp