SLOTH: KKS< T > Class Template Reference
KKS< T > Class Template Reference
Linearized KKS problem for two-phase multi-component system.
#include <KKS.hpp>
Public Member Functions
void clear_containers ()
Clear containers used to store the results of equilibrium calculations.
void execute_linearization (CalphadBase< T > &CALPHAD, const int dt, const double time_step, const std::vector< T > &tp_gf, const std::vector< T > &tp_gf_old, const std::tuple< std::string, T, T > &phasefields_gf, const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, const std::vector< std::tuple< std::string, std::string, T, T >> &x_gf, const std::vector< std::tuple< std::string, T >> &coord_gf)
Compute Calphad contributions needed by KKS resolution.
void get_parameters (const CalphadBase< T > &CALPHAD)
Get all parameters required by KKS problem.
KKS ()
Construct a new Calphad Base< T>:: Calphad Base object.
virtual ~KKS ()
Destroy the Calphad Base< T>:: Calphad Base object.
Protected Member Functions
std::unique_ptr< mfem::SparseMatrix > get_A4linearKKS (const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, const std::string &phase, const int node)
Second order finite difference approximation.
mfem::Vector get_h4linearKKS (const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, const std::string &phase, const int node)
Second order finite difference approximation (cross derivatives)
mfem::Vector get_m4linearKKS (const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, const std::string &phase, const int node)
First order finite difference approximation.
Protected Attributes
std::map< std::tuple< int, std::string, std::string >, double > chemical_potentials_by_phase_
std::map< std::tuple< int, std::string, std::string >, double > chemical_potentials_left_T_
std::map< std::tuple< int, int, std::string, std::string >, double > chemical_potentials_left_x_
std::map< std::tuple< int, std::string, std::string >, double > chemical_potentials_right_T_
std::map< std::tuple< int, int, std::string, std::string >, double > chemical_potentials_right_x_
std::shared_ptr< CalphadUtils< T > > CU_
std::string element_removed_from_ic_
PotentialFunctions< 0, ThermodynamicsPotentialDiscretization::Implicit, ThermodynamicsPotentials::H > interpolation_func_
double KKS_composition_increment_
bool KKS_freeze_nucleation_ {true}
double KKS_mobility_for_seed_
bool KKS_nucleation_started_ {false}
std::string KKS_secondary_phase_
double KKS_seed_
double KKS_seed_radius_
double KKS_temperature_increment_
bool KKS_temperature_scheme_
double KKS_temperature_threshold_
double KKS_threshold_
Detailed Description
template<typename T>
class KKS< T >
Linearized KKS problem for two-phase multi-component system.
Template Parameters
T
Definition at line 53 of file KKS.hpp.
Constructor & Destructor Documentation
KKS()
template<typename T > KKS< T >::KKS
Construct a new Calphad Base< T>:: Calphad Base object.
Template Parameters
T
Definition at line 171 of file KKS.hpp.
~KKS()
template<typename T > KKS< T >::~KKS virtual
Destroy the Calphad Base< T>:: Calphad Base object.
Template Parameters
T
Definition at line 1039 of file KKS.hpp.
Member Function Documentation
clear_containers()
template<typename T > void KKS< T >::clear_containers
Clear containers used to store the results of equilibrium calculations.
Template Parameters
T
Definition at line 1024 of file KKS.hpp.
execute_linearization()
template<typename T > void KKS< T >::execute_linearization (CalphadBase< T > & CALPHAD, const int dt, const double time_step, const std::vector< T > & tp_gf, const std::vector< T > & tp_gf_old, const std::tuple< std::string, T, T > & phasefields_gf, const std::vector< std::tuple< std::string, std::string >> & chemicalsystem, const std::vector< std::tuple< std::string, std::string, T, T >> & x_gf, const std::vector< std::tuple< std::string, T >> & coordinates)
Compute Calphad contributions needed by KKS resolution.
Template Parameters
T The type of the template parameter (mfem::Vector or std::vector)
Parameters
CALPHAD The CALPHAD object for thermodynamic calculation
dt The time step for the simulation.
tp_gf The thermodynamic conditions at the current time step.
tp_gf_old The thermodynamic conditions at the previous time step.
phasefields_gf The phase-field at the current and previous time-step
chemicalsystem The targeted chemical system
x_gf The mole fraction of compoenent at the current and previous time-step
Point of expansion (Tbar,Xbar)
Calculation of all thermodynamic contributions
Primary phase
Secondary phase (if exists)
Interface (if exists)
Solve linear systems
Recover thermodynamic contribution
Definition at line 285 of file KKS.hpp.
References CalphadBase< T >::chemical_potentials_, Debug, SlothInfo::debug(), CalphadBase< T >::diffusion_chemical_potentials_, CalphadBase< T >::driving_forces_, CalphadBase< T >::elem_mole_fraction_by_phase_, CalphadBase< T >::energies_of_phases_, CalphadBase< T >::error_equilibrium_, CalphadDefaultConstant::error_max, CalphadBase< T >::execute(), KKS_nucleation_strategy::from(), H, KKS_nucleation_strategy::liquid_fraction, CalphadBase< T >::nucleus_, SlothInfo::print(), CalphadBase< T >::time_specialized_, and verbosityLevel.
get_A4linearKKS()
template<typename T > std::unique_ptr< mfem::SparseMatrix > KKS< T >::get_A4linearKKS (const std::vector< std::tuple< std::string, std::string >> & chemicalsystem, const std::string & phase, const int node) protected
Second order finite difference approximation.
Template Parameters
T The type of the template parameter (mfem::Vector or std::vector)
Parameters
chemicalsystem The targeted chemical system
phase The phase for which derivatives are computed
node The node where calculation are done
Returns
mfem::SparseMatrix*
Definition at line 880 of file KKS.hpp.
get_h4linearKKS()
template<typename T > mfem::Vector KKS< T >::get_h4linearKKS (const std::vector< std::tuple< std::string, std::string >> & chemicalsystem, const std::string & phase, const int node) protected
Second order finite difference approximation (cross derivatives)
Template Parameters
T The type of the template parameter (mfem::Vector or std::vector)
Parameters
chemicalsystem The targeted chemical system
phase The phase for which derivatives are computed
node The node where calculation are done
Returns
mfem::Vector
Definition at line 996 of file KKS.hpp.
get_m4linearKKS()
template<typename T > mfem::Vector KKS< T >::get_m4linearKKS (const std::vector< std::tuple< std::string, std::string >> & chemicalsystem, const std::string & phase, const int node) protected
First order finite difference approximation.
Template Parameters
T The type of the template parameter (mfem::Vector or std::vector)
Parameters
chemicalsystem The targeted chemical system
phase The phase for which derivatives are computed
node The node where calculation are done
Returns
mfem::Vector
Definition at line 967 of file KKS.hpp.
get_parameters()
template<typename T > void KKS< T >::get_parameters (const CalphadBase< T > & CALPHAD)
Get all parameters required by KKS problem.
Template Parameters
T
Definition at line 181 of file KKS.hpp.
References CalphadBase< T >::element_removed_from_ic_, KKS_nucleation_strategy::from(), KKS_nucleation_strategy::given_melting_temperature, and CalphadBase< T >::params_.
Member Data Documentation
chemical_potentials_by_phase_
template<typename T > std::map<std::tuple<int, std::string, std::string>, double> KKS< T >::chemical_potentials_by_phase_ protected
Definition at line 142 of file KKS.hpp.
chemical_potentials_left_T_
template<typename T > std::map<std::tuple<int, std::string, std::string>, double> KKS< T >::chemical_potentials_left_T_ protected
Definition at line 143 of file KKS.hpp.
chemical_potentials_left_x_
template<typename T > std::map<std::tuple<int, int, std::string, std::string>, double> KKS< T >::chemical_potentials_left_x_ protected
Definition at line 144 of file KKS.hpp.
chemical_potentials_right_T_
template<typename T > std::map<std::tuple<int, std::string, std::string>, double> KKS< T >::chemical_potentials_right_T_ protected
Definition at line 145 of file KKS.hpp.
chemical_potentials_right_x_
template<typename T > std::map<std::tuple<int, int, std::string, std::string>, double> KKS< T >::chemical_potentials_right_x_ protected
Definition at line 146 of file KKS.hpp.
CU_
template<typename T > std::shared_ptr<CalphadUtils<T> > KKS< T >::CU_ protected
Definition at line 76 of file KKS.hpp.
element_removed_from_ic_
template<typename T > std::string KKS< T >::element_removed_from_ic_ protected
Definition at line 80 of file KKS.hpp.
interpolation_func_
template<typename T > PotentialFunctions<0, ThermodynamicsPotentialDiscretization::Implicit, ThermodynamicsPotentials::H> KKS< T >::interpolation_func_ protected
Definition at line 124 of file KKS.hpp.
KKS_composition_increment_
template<typename T > double KKS< T >::KKS_composition_increment_ protected
Definition at line 99 of file KKS.hpp.
KKS_freeze_nucleation_
template<typename T > bool KKS< T >::KKS_freeze_nucleation_ {true} protected
Definition at line 119 of file KKS.hpp.
KKS_mobility_for_seed_
template<typename T > double KKS< T >::KKS_mobility_for_seed_ protected
Definition at line 86 of file KKS.hpp.
KKS_nucleation_started_
template<typename T > bool KKS< T >::KKS_nucleation_started_ {false} protected
Definition at line 115 of file KKS.hpp.
KKS_secondary_phase_
template<typename T > std::string KKS< T >::KKS_secondary_phase_ protected
Definition at line 83 of file KKS.hpp.
KKS_seed_
template<typename T > double KKS< T >::KKS_seed_ protected
Definition at line 89 of file KKS.hpp.
KKS_seed_radius_
template<typename T > double KKS< T >::KKS_seed_radius_ protected
Definition at line 92 of file KKS.hpp.
KKS_temperature_increment_
template<typename T > double KKS< T >::KKS_temperature_increment_ protected
Definition at line 95 of file KKS.hpp.
KKS_temperature_scheme_
template<typename T > bool KKS< T >::KKS_temperature_scheme_ protected
Definition at line 112 of file KKS.hpp.
KKS_temperature_threshold_
template<typename T > double KKS< T >::KKS_temperature_threshold_ protected
Definition at line 107 of file KKS.hpp.
KKS_threshold_
template<typename T > double KKS< T >::KKS_threshold_ protected
Definition at line 102 of file KKS.hpp.
The documentation for this class was generated from the following files:
CalphadBase.hpp
KKS.hpp