SLOTH: Parameters Class Reference
Parameters Class Reference
#include <Parameters.hpp>
Public Member Functions
template<typename T >
T get_param_value (const std::string &name) const
Return the value of the parameter associated to the given name.
template<typename T >
T get_param_value_or_default (const std::string &name, T default_value) const
Return the value of the parameter associated to the given name or, use th edefault given, value.
std::optional< Parameter > get_parameter (const std::string &name) const
Return the parameter associated to the given name.
int get_size () const
Return the size of a Parameters.
std::vector< Parameter > get_vector () const
Return a vector of Parameter.
bool has_parameter (const std::string &param_name) const
Search a parameter by its name.
Parameters operator+ (const Parameter &param) const
Add a parameter inside a Parameters. If param already exists, the given parameters overwrites the existing one.
Parameters operator+ (const Parameters &params) const
Add two Parameters with a priority given to the second Parameters to overwrite Parameter objets in the first Parameters if already exist.
Parameters operator- (const Parameter &param) const
Remove a parameter inside a Parameters if exists.
template<typename... Args>
Parameters (Args &&... args)
Construct a new Parameters:: Parameters object.
Parameters (const std::vector< Parameter > &vect_params)
Construct a new Parameters:: Parameters object.
~Parameters ()
Destroy the Parameters:: Parameters object.
Detailed Description
Definition at line 40 of file Parameters.hpp.
Constructor & Destructor Documentation
Parameters() [1/2]
template<typename... Args> Parameters::Parameters (Args &&... args) explicit
Construct a new Parameters:: Parameters object.
Template Parameters
Args
Parameters
args
Definition at line 131 of file Parameters.hpp.
Referenced by operator+(), and operator-().
Parameters() [2/2]
Parameters::Parameters (const std::vector< Parameter > & vect_params) explicit
Construct a new Parameters:: Parameters object.
Parameters
vect_params
Definition at line 140 of file Parameters.hpp.
~Parameters()
Parameters::~Parameters ()
Destroy the Parameters:: Parameters object.
Definition at line 248 of file Parameters.hpp.
Member Function Documentation
get_param_value()
template<typename T > T Parameters::get_param_value (const std::string & name) const
Return the value of the parameter associated to the given name.
Parameters
name
Returns
std::variant<int, double, std::string>
Definition at line 225 of file Parameters.hpp.
References get_parameter(), and Parameter::get_value().
Referenced by SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), PrecondHypreDiagScale::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), NLSolverBase::create_solver(), PrecondDSmoother::create_solver(), Conductivity_function< 0 >::getConstant(), density_function< 0 >::getConstant(), Diffusion_function< 0 >::getConstant(), HeatCapacity_function< 0 >::getConstant(), Lambda_function< 0 >::getConstant(), Mobility_function< 0 >::getConstant(), Omega_function< 0 >::getConstant(), Mobility_function< 0 >::getDegenerated(), Mobility_function< 1 >::getDegenerated(), Conductivity_function< 0 >::getLinear(), Conductivity_function< 1 >::getLinear(), density_function< 0 >::getLinear(), density_function< 1 >::getLinear(), Diffusion_function< 0 >::getLinear(), Diffusion_function< 1 >::getLinear(), HeatCapacity_function< 0 >::getLinear(), HeatCapacity_function< 1 >::getLinear(), Diffusion_function< 0 >::getLog(), and Diffusion_function< 1 >::getLog().
get_param_value_or_default()
template<typename T > T Parameters::get_param_value_or_default (const std::string & name, T default_value) const
Return the value of the parameter associated to the given name or, use th edefault given, value.
Parameters
name
default_value
Returns
std::variant<int, double, std::string>
Definition at line 194 of file Parameters.hpp.
References get_parameter(), and Parameter::get_value().
Referenced by SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), NLSolverBase::create_solver(), and PrecondDSmoother::create_solver().
get_parameter()
std::optional< Parameter > Parameters::get_parameter (const std::string & name) const
Return the parameter associated to the given name.
Parameters
name
Returns
Parameter
Definition at line 177 of file Parameters.hpp.
Referenced by get_param_value(), and get_param_value_or_default().
get_size()
int Parameters::get_size () const
Return the size of a Parameters.
Template Parameters
Args
Returns
in
Definition at line 169 of file Parameters.hpp.
get_vector()
std::vector< Parameter > Parameters::get_vector () const
Return a vector of Parameter.
Template Parameters
Args
Returns
std::vector<Parameter>
Definition at line 148 of file Parameters.hpp.
Referenced by operator+(), and operator-().
has_parameter()
bool Parameters::has_parameter (const std::string & param_name) const
Search a parameter by its name.
Parameters
param_name
Returns
true
false
Definition at line 157 of file Parameters.hpp.
operator+() [1/2]
Parameters Parameters::operator+ (const Parameter & param) const inline
Add a parameter inside a Parameters. If param already exists, the given parameters overwrites the existing one.
Parameters
param
Returns
Parameters
Definition at line 93 of file Parameters.hpp.
References get_vector(), and Parameters().
operator+() [2/2]
Parameters Parameters::operator+ (const Parameters & params) const inline
Add two Parameters with a priority given to the second Parameters to overwrite Parameter objets in the first Parameters if already exist.
Parameters
params
Returns
Parameters
Definition at line 68 of file Parameters.hpp.
References get_vector(), and Parameters().
operator-()
Parameters Parameters::operator- (const Parameter & param) const inline
Remove a parameter inside a Parameters if exists.
Parameters
param
Returns
Parameters
Definition at line 111 of file Parameters.hpp.
References get_vector(), and Parameters().
The documentation for this class was generated from the following file:
Parameters.hpp