SLOTH: DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME > Class Template Reference
DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME > Class Template Reference
Class dedicated to the FV of the mass diffusion equation.
#include <DiffusionNLFormIntegrator.hpp>
Public Member Functions
virtual void AssembleElementGrad (const mfem::Array< const mfem::FiniteElement * > &el, mfem::ElementTransformation &Tr, const mfem::Array< const mfem::Vector * > &elfun, const mfem::Array2D< mfem::DenseMatrix * > &elmat)
Jacobian part of the non linear problem.
virtual void AssembleElementVector (const mfem::Array< const mfem::FiniteElement * > &el, mfem::ElementTransformation &Tr, const mfem::Array< const mfem::Vector * > &elfun, const mfem::Array< mfem::Vector * > &elvect)
Residual part of the non linear problem.
DiffusionNLFormIntegrator (const std::vector< mfem::ParGridFunction > &u_old, const Parameters &params, std::vector< VARS * > auxvars)
Construct a new DiffusionNLFormIntegrator<SCHEME, COEFFICIENT>::DiffusionNLFormIntegrator object.
std::unique_ptr< HomogeneousEnergyCoefficient< ThermodynamicsPotentials::LOG > > get_energy (std::vector< mfem::ParGridFunction * > gfu, const double diffu)
~DiffusionNLFormIntegrator ()
Destroy the DiffusionNLFormIntegrator<SCHEME, COEFFICIENT>::DiffusionNLFormIntegrator.
Public Member Functions inherited from SlothNLFormIntegrator< VARS >
SlothNLFormIntegrator (const Parameters &params, std::vector< VARS * > auxvars)
Construct a new SlothNLFormIntegrator::SlothNLFormIntegrator object.
~SlothNLFormIntegrator ()
Destroy the SlothNLFormIntegrator::SlothNLFormIntegrator object.
Additional Inherited Members
Protected Member Functions inherited from SlothNLFormIntegrator< VARS >
std::vector< mfem::ParGridFunction > get_aux_gf ()
Return a vector of GridFunction associated with auxiliary variables.
std::vector< std::vector< std::string > > get_aux_infos ()
Return a vector of the additional information (vector of string) associated with auxiliary variables.
std::vector< mfem::Vector > get_aux_old_gf ()
Return a vector of GridFunction associated with auxiliary variables at the previous time-step.
Protected Attributes inherited from SlothNLFormIntegrator< VARS >
std::vector< VARS * > auxvariables_
const Parameters params_
Detailed Description
template<class VARS, CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME>
class DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >
Class dedicated to the FV of the mass diffusion equation.
Template Parameters
SCHEME
DIFFU_NAME
Definition at line 49 of file DiffusionNLFormIntegrator.hpp.
Constructor & Destructor Documentation
DiffusionNLFormIntegrator()
template<class VARS , CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME> DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >::DiffusionNLFormIntegrator (const std::vector< mfem::ParGridFunction > & u_old, const Parameters & params, std::vector< VARS * > auxvars)
Construct a new DiffusionNLFormIntegrator<SCHEME, COEFFICIENT>::DiffusionNLFormIntegrator object.
Template Parameters
SCHEME
COEFFICIENT
Parameters
u_old
alpha
kappa
Definition at line 152 of file DiffusionNLFormIntegrator.hpp.
References SlothNLFormIntegrator< VARS >::get_aux_gf(), SlothNLFormIntegrator< VARS >::get_aux_infos(), and SlothNLFormIntegrator< VARS >::get_aux_old_gf().
~DiffusionNLFormIntegrator()
template<class VARS , CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME> DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >::~DiffusionNLFormIntegrator
Destroy the DiffusionNLFormIntegrator<SCHEME, COEFFICIENT>::DiffusionNLFormIntegrator.
Template Parameters
SCHEME
COEFFICIENT
Definition at line 270 of file DiffusionNLFormIntegrator.hpp.
Member Function Documentation
AssembleElementGrad()
template<class VARS , CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME> void DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >::AssembleElementGrad (const mfem::Array< const mfem::FiniteElement * > & el, mfem::ElementTransformation & Tr, const mfem::Array< const mfem::Vector * > & elfun, const mfem::Array2D< mfem::DenseMatrix * > & elmat) virtual
Jacobian part of the non linear problem.
Parameters
el
Tr
elfun
elmat
Definition at line 214 of file DiffusionNLFormIntegrator.hpp.
AssembleElementVector()
template<class VARS , CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME> void DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >::AssembleElementVector (const mfem::Array< const mfem::FiniteElement * > & el, mfem::ElementTransformation & Tr, const mfem::Array< const mfem::Vector * > & elfun, const mfem::Array< mfem::Vector * > & elvect) virtual
Residual part of the non linear problem.
Parameters
el
Tr
elfun
elvect
Definition at line 171 of file DiffusionNLFormIntegrator.hpp.
get_energy()
template<class VARS , CoefficientDiscretization SCHEME, Diffusion DIFFU_NAME> std::unique_ptr< HomogeneousEnergyCoefficient< ThermodynamicsPotentials::LOG > > DiffusionNLFormIntegrator< VARS, SCHEME, DIFFU_NAME >::get_energy (std::vector< mfem::ParGridFunction * > gfu, const double diffu)
Definition at line 256 of file DiffusionNLFormIntegrator.hpp.
The documentation for this class was generated from the following file:
DiffusionNLFormIntegrator.hpp