SLOTH: SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI > Class Template Reference
SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI > Class Template Reference abstract
SteadyOperatorBase class.
#include <SteadyOperatorBase.hpp>
Public Member Functions
void ComputeEnergies (const int &it, const double &t, const double &dt, const std::vector< mfem::Vector > &u) override=0
void get_parameters () override=0
void initialize (const double &initial_time, Variables< T, DIM > &vars, std::vector< Variables< T, DIM > * > auxvars) override
Initialization stage (call by imeDiscretization<PST, OPE, VAR>::initialize())
void Mult (const mfem::Vector &k, mfem::Vector &y) const override
Compute RHS.
void set_default_properties () override=0
NLFI * set_nlfi_ptr (const double dt, const std::vector< mfem::Vector > &u) override=0
void SetConstantParameters (const double dt, const std::vector< mfem::Vector > &u_vect) override
Set current dt, unk values - needed to compute action and Jacobian.
void SetTransientParameters (const double dt, const std::vector< mfem::Vector > &u_vet) override
Set current dt, unk values - needed to compute action and Jacobian. solution_coef.
void solve (std::vector< std::unique_ptr< mfem::Vector >> &vect_unk, double &next_time, const double &current_time, double dt, const int iter) override
Solve the steady problem.
SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials)
Construct a new SteadyOperatorBase object.
SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params)
Construct a new SteadyOperatorBase object.
SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params, std::vector< AnalyticalFunctions< DIM >> source_term_name)
Construct a new SteadyOperatorBase object.
SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, std::vector< AnalyticalFunctions< DIM >> source_term_name)
Construct a new SteadyOperatorBase object.
virtual ~SteadyOperatorBase ()
Destroy the Steady Phase Field Operator Base< T, DIM, NLFI>:: Steady Phase Field Operator Base object.
Public Member Functions inherited from OperatorBase< T, DIM, NLFI, LHS_NLFI >
void clear_iso_time_specialized ()
Clear time_iso_specialized_ container.
void clear_time_specialized ()
Clear time_specialized_ container.
void ComputeError (const int &it, const double &t, const double &dt, const int id_var, const std::string &name, const mfem::Vector &u, std::function< double(const mfem::Vector &, double)> solution_func)
Compute L2 error.
void ComputeIntegral (const int &it, const double &t, const double &dt, const int id_var, const std::string &name, const mfem::Vector &u, const double lower_bound, const double upper_bound)
Compute integrals of a variable over the domain.
void ComputeIsoVal (const int &it, const double &t, const double &dt, const int var_id, const std::string &var_name, const mfem::Vector &u, const double &iso_value)
Compute the position of an isovalue.
std::string get_description ()
void get_source_term (const int id_block, const std::function< double(const mfem::Vector &, double)> &src_func, mfem::Vector &source_term, mfem::ParLinearForm *RHHS) const
Get the source term by equation of the PDEs.
const std::map< std::string, std::multimap< IterationKey, SpecializedValue > > get_time_iso_specialized () const
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
const std::multimap< IterationKey, SpecializedValue > get_time_specialized () const
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials)
Construct a new OperatorBase object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params)
Construct a new OperatorBase object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params, const std::vector< AnalyticalFunctions< DIM >> &source_term_name)
Construct a new Phase Field Operator Base< T, DIM, NLFI>:: Phase Field Operator Base object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const std::vector< AnalyticalFunctions< DIM >> &source_term_name)
Construct a new OperatorBase object.
void overload_nl_solver (NLSolverType NLSOLVER)
Overload the nonlinear algorithm.
void overload_nl_solver (NLSolverType NLSOLVER, const Parameters &nl_params)
Overload Parameters associated with nonlinear algorithm.
void overload_preconditioner (VSolverType PRECOND)
Overload the preconditioner used by the solver in the NL algorithm.
void overload_preconditioner (VSolverType PRECOND, const Parameters &p_params)
Overload the parameters of the preconditioner used by the solver in the NL algorithm.
void overload_solver (VSolverType SOLVER)
Overload the default linear solver used for the LHS.
void overload_solver (VSolverType SOLVER, const Parameters &s_params)
Overload the parameter for the linear solver used for the LHS.
virtual ~OperatorBase ()
Destroy the Operator Base<T, DIM, NLFI>:: Operator Base object.
Additional Inherited Members
Protected Member Functions inherited from OperatorBase< T, DIM, NLFI, LHS_NLFI >
void build_rhs_nonlinear_form (const double dt, const std::vector< mfem::Vector > &u)
Build the NonLinear Form Integrator associated with the RHS of the PDEs.
int compute_total_height (const std::vector< SpatialDiscretization< T, DIM > * > &spatials)
Return the total height (output=rows of Operator) of the PDE system.
int compute_total_width (const std::vector< SpatialDiscretization< T, DIM > * > &spatials)
Return the total width (input=column of Operator) of the PDE system.
void SetNewtonAlgorithm (mfem::Operator *oper)
Configure the Newton solver.
Protected Attributes inherited from OperatorBase< T, DIM, NLFI, LHS_NLFI >
std::vector< Variables< T, DIM > * > auxvariables_
std::vector< BoundaryConditions< T, DIM > * > bcs_
Boundary conditions.
mfem::Array< int > block_trueOffsets_
double current_dt_
double current_time_
const Parameter default_p_ = Parameter("default parameter", false)
const Parameters default_params_ = Parameters(default_p_)
std::string description_ {"UNKNOWN OPERATOR"}
std::vector< mfem::Array< int > > ess_tdof_list_
mfem::Array< mfem::ParFiniteElementSpace * > fes_
Finite Element Space and BCs.
int height_
std::shared_ptr< mfem::NewtonSolver > newton_solver_
NLFI * nlfi_ptr_
const Parameters & params_
mfem::ParBlockNonlinearForm * RHS
Right-Hand-Side.
NLSolver * rhs_solver_
std::vector< std::function< double(const mfem::Vector &, double)> > src_func_
std::map< std::string, std::multimap< IterationKey, SpecializedValue > > time_iso_specialized_
std::multimap< IterationKey, SpecializedValue > time_specialized_
Time integral results.
mfem::Vector z
Detailed Description
template<class T, int DIM, class NLFI, class LHS_NLFI>
class SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >
SteadyOperatorBase class.
Definition at line 50 of file SteadyOperatorBase.hpp.
Constructor & Destructor Documentation
SteadyOperatorBase() [1/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials) explicit
Construct a new SteadyOperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
Definition at line 100 of file SteadyOperatorBase.hpp.
References NEWTON, and OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver().
SteadyOperatorBase() [2/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, std::vector< AnalyticalFunctions< DIM >> source_term_name)
Construct a new SteadyOperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
source_term_name
Definition at line 118 of file SteadyOperatorBase.hpp.
References NEWTON, and OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver().
SteadyOperatorBase() [3/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters & params)
Construct a new SteadyOperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
params
Definition at line 137 of file SteadyOperatorBase.hpp.
References NEWTON, and OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver().
SteadyOperatorBase() [4/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SteadyOperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters & params, std::vector< AnalyticalFunctions< DIM >> source_term_name)
Construct a new SteadyOperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
params
source_term_name
Definition at line 156 of file SteadyOperatorBase.hpp.
References NEWTON, and OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver().
~SteadyOperatorBase()
template<class T , int DIM, class NLFI , class LHS_NLFI > SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::~SteadyOperatorBase virtual
Destroy the Steady Phase Field Operator Base< T, DIM, NLFI>:: Steady Phase Field Operator Base object.
Template Parameters
T
DIM
NLFI
Definition at line 324 of file SteadyOperatorBase.hpp.
Member Function Documentation
ComputeEnergies()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::ComputeEnergies (const int & it, const double & t, const double & dt, const std::vector< mfem::Vector > & u) override pure virtual
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Implemented in PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >.
get_parameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::get_parameters () override pure virtual
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Implemented in PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >.
initialize()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::initialize (const double & initial_time, Variables< T, DIM > & vars, std::vector< Variables< T, DIM > * > auxvars) override virtual
Initialization stage (call by imeDiscretization<PST, OPE, VAR>::initialize())
Template Parameters
T
DIM
NLFI
Parameters
initial_time
vars
Reimplemented from OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Definition at line 176 of file SteadyOperatorBase.hpp.
References OperatorBase< T, DIM, NLFI, LHS_NLFI >::initialize().
Mult()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::Mult (const mfem::Vector & k, mfem::Vector & y) const override
Compute RHS.
Template Parameters
T
DIM
NLFI
Parameters
k
y
Definition at line 310 of file SteadyOperatorBase.hpp.
set_default_properties()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::set_default_properties () override pure virtual
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Implemented in PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, SteadyPhaseFieldOperator< T, DIM, NLFI, LHS_NLFI >, SteadyHeatOperator< T, DIM, NLFI, LHS_NLFI >, and SteadyDiffusionOperator< T, DIM, NLFI, LHS_NLFI >.
set_nlfi_ptr()
template<class T , int DIM, class NLFI , class LHS_NLFI > NLFI* SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::set_nlfi_ptr (const double dt, const std::vector< mfem::Vector > & u) override pure virtual
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Implemented in PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >.
SetConstantParameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SetConstantParameters (const double dt, const std::vector< mfem::Vector > & u_vect) override virtual
Set current dt, unk values - needed to compute action and Jacobian.
Template Parameters
T
DIM
NLFI
Parameters
dt
u
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Definition at line 261 of file SteadyOperatorBase.hpp.
SetTransientParameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SetTransientParameters (const double dt, const std::vector< mfem::Vector > & u_vect) override virtual
Set current dt, unk values - needed to compute action and Jacobian. solution_coef.
Parameters
dt time-step
u unknown vector
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Definition at line 273 of file SteadyOperatorBase.hpp.
solve()
template<class T , int DIM, class NLFI , class LHS_NLFI > void SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::solve (std::vector< std::unique_ptr< mfem::Vector >> & vect_unk, double & next_time, const double & current_time, double dt, const int iter) override virtual
Solve the steady problem.
Template Parameters
T
DIM
NLFI
Parameters
unk
current_time
dt
Apply BCs: check if need to be uncomment
Implements OperatorBase< T, DIM, NLFI, LHS_NLFI >.
Definition at line 194 of file SteadyOperatorBase.hpp.
The documentation for this class was generated from the following file:
SteadyOperatorBase.hpp