SLOTH: SlothSolver Class Reference
SlothSolver Class Reference
Base class used to manage linear and non linear solvers.
#include <SlothSolver.hpp>
Public Member Functions
VSharedMFEMSolver get_value ()
Create the linear solver depending on SolverType.
SlothSolver (VSolverType value, const Parameters &params)
Construct a new SlothSolver object.
~SlothSolver ()
Destroy the SlothSolver object.
Detailed Description
Base class used to manage linear and non linear solvers.
Definition at line 279 of file SlothSolver.hpp.
Constructor & Destructor Documentation
SlothSolver()
SlothSolver::SlothSolver (VSolverType value, const Parameters & params)
Construct a new SlothSolver object.
Parameters
value : type of solver (see VSolverType for a list of available solvers)
params
Definition at line 297 of file SlothSolver.hpp.
~SlothSolver()
SlothSolver::~SlothSolver ()
Destroy the SlothSolver object.
Definition at line 403 of file SlothSolver.hpp.
Member Function Documentation
get_value()
VSharedMFEMSolver SlothSolver::get_value ()
Create the linear solver depending on SolverType.
Returns
VSharedMFEMSolver
Definition at line 305 of file SlothSolver.hpp.
References BICGSTAB, CG, SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), PrecondHypreDiagScale::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), PrecondDSmoother::create_solver(), GMRES, HYPRE_BOOMER_AMG, HYPRE_DIAG_SCALE, HYPRE_FGMRES, HYPRE_GMRES, HYPRE_ILU, HYPRE_PCG, HYPRE_SMOOTHER, MINRES, NO, SMOOTHER, and UMFPACK.
The documentation for this class was generated from the following file:
SlothSolver.hpp