SLOTH: ProblemBase< VAR, PST > Class Template Reference
ProblemBase< VAR, PST > Class Template Reference abstract
#include <ProblemBase.hpp>
Public Member Functions
virtual void do_time_step (double &next_time, const double &current_time, double current_time_step, const int iter, std::vector< std::unique_ptr< mfem::Vector >> &unks, const std::vector< std::vector< std::string >> &unks_info)=0
Main actions done during a time-step.
void execute (const int &iter, double &next_time, const double &current_time, const double &current_time_step)
Execute step.
virtual void finalize ()
Finalize the problem.
std::vector< std::tuple< std::string, bool, double > > get_convergence ()
Return for each variable, a tuple (string,string, boolean, double) where the boolean is the flag indicating if the criterion is reached or not, and the double is the criterion reached. The first string is the name of the problem, and the second the name of the variable.
std::string get_name ()
Returns the name of the problem.
VAR get_problem_variables ()
Return the variables associated with the problem.
virtual void initialize (const double &initial_time)
Initialize the problem.
virtual void post_execute (const int &iter, const double &current_time, const double &current_time_step)
Performs actions after the execute step.
virtual void post_processing (const int &iter, const double &current_time, const double &current_time_step)
Save variables of the problem (see save method for other actions)
template<class... Args>
ProblemBase (const std::string &name, VAR &variables, PST &pst, Args &&... auxvariables)
Constructs a new ProblemBase object.
template<class... Args>
ProblemBase (const std::string &name, VAR &variables, PST &pst, Convergence &convergence, Args &&... auxvariables)
Constructs a new ProblemBase object.
template<class... Args>
ProblemBase (const std::string &name, VAR &variables, PST &pst, Convergence &convergence, std::list< int > pop_elem, Args &&... auxvariables)
Constructs a new ProblemBase object.
template<class... Args>
ProblemBase (const std::string &name, VAR &variables, PST &pst, std::list< int > pop_elem, Args &&... auxvariables)
Constructs a new ProblemBase object.
void save (const int &iter, const double &current_time)
Save variables.
void update ()
Update the variables associated with the problem.
virtual ~ProblemBase ()
Destroy the ProblemBase<VAR, PST>::ProblemBase object.
Protected Attributes
std::vector< VAR * > auxvariables_
std::shared_ptr< Convergence > convergence_
std::string name_ {"Unnamed problem"}
const std::list< int > pop_elem_
PST & pst_
std::vector< mfem::Vector > unknown_
std::vector< std::tuple< std::string, bool, double > > var_convergence_
VAR & variables_
Detailed Description
template<class VAR, class PST>
class ProblemBase< VAR, PST >
Definition at line 49 of file ProblemBase.hpp.
Constructor & Destructor Documentation
ProblemBase() [1/4]
template<class VAR , class PST > template<class... Args> ProblemBase< VAR, PST >::ProblemBase (const std::string & name, VAR & variables, PST & pst, Convergence & convergence, std::list< int > pop_elem, Args &&... auxvariables)
Constructs a new ProblemBase object.
Initializes a Problem instance
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Args Types of auxiliary variables passed variadically.
Parameters
name Name of the problem.
variables Reference to the Variables object.
pst Reference to the PostProcessing object.
convergence Reference to the Convergence object.
pop_elem List of elements to remove from Variables.
auxvariables Variadic pack of auxiliary variables.
Definition at line 133 of file ProblemBase.hpp.
References ProblemBase< VAR, PST >::auxvariables_, ProblemBase< VAR, PST >::convergence_, and ProblemBase< VAR, PST >::pop_elem_.
ProblemBase() [2/4]
template<class VAR , class PST > template<class... Args> ProblemBase< VAR, PST >::ProblemBase (const std::string & name, VAR & variables, PST & pst, std::list< int > pop_elem, Args &&... auxvariables)
Constructs a new ProblemBase object.
Initializes a Problem instance
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Args Types of auxiliary variables passed variadically.
Parameters
name Name of the problem.
variables Reference to the Variables object.
pst Reference to the PostProcessing object.
pop_elem List of elements to remove from Variables.
auxvariables Variadic pack of auxiliary variables.
Definition at line 174 of file ProblemBase.hpp.
References ProblemBase< VAR, PST >::auxvariables_, and ProblemBase< VAR, PST >::pop_elem_.
ProblemBase() [3/4]
template<class VAR , class PST > template<class... Args> ProblemBase< VAR, PST >::ProblemBase (const std::string & name, VAR & variables, PST & pst, Convergence & convergence, Args &&... auxvariables)
Constructs a new ProblemBase object.
Initializes a Problem instance
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Args Types of auxiliary variables passed variadically.
Parameters
name Name of the problem.
variables Reference to the Variables object.
pst Reference to the PostProcessing object.
convergence Reference to the Convergence object.
auxvariables Variadic pack of auxiliary variables.
Definition at line 213 of file ProblemBase.hpp.
References ProblemBase< VAR, PST >::auxvariables_, and ProblemBase< VAR, PST >::convergence_.
ProblemBase() [4/4]
template<class VAR , class PST > template<class... Args> ProblemBase< VAR, PST >::ProblemBase (const std::string & name, VAR & variables, PST & pst, Args &&... auxvariables)
Constructs a new ProblemBase object.
Initializes a Problem instance
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Args Types of auxiliary variables passed variadically.
Parameters
name Name of the problem.
variables Reference to the Variables object.
pst Reference to the PostProcessing object.
auxvariables Variadic pack of auxiliary variables.
Definition at line 240 of file ProblemBase.hpp.
References ProblemBase< VAR, PST >::auxvariables_.
~ProblemBase()
template<class VAR , class PST > ProblemBase< VAR, PST >::~ProblemBase virtual
Destroy the ProblemBase<VAR, PST>::ProblemBase object.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Definition at line 475 of file ProblemBase.hpp.
Member Function Documentation
do_time_step()
template<class VAR , class PST > void ProblemBase< VAR, PST >::do_time_step (double & next_time, const double & current_time, double current_time_step, const int iter, std::vector< std::unique_ptr< mfem::Vector >> & unks, const std::vector< std::vector< std::string >> & unks_info) pure virtual
Main actions done during a time-step.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
next_time Next simulation time (Current time+ current time step).
current_time Current simulation time.
current_time_step Current time-step.
iter Current iteration number.
unks Unknown at the current time-step.
unks_info Additionnal informations associated with the unkwon of the Problem.
Implemented in Property_problem< PROPERTY, VAR, PST >, Problem< OPE, VAR, PST >, MPI_Problem< VAR, PST >, and Calphad_Problem< CALPHAD, VAR, PST >.
Definition at line 397 of file ProblemBase.hpp.
execute()
template<class VAR , class PST > void ProblemBase< VAR, PST >::execute (const int & iter, double & next_time, const double & current_time, const double & current_time_step)
Execute step.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
iter Current iteration number.
next_time Next simulation time (Current time+ current time step).
current_time Current simulation time.
current_time_step Current time-step.
Definition at line 327 of file ProblemBase.hpp.
References SlothInfo::verbose().
finalize()
template<class VAR , class PST > void ProblemBase< VAR, PST >::finalize virtual
Finalize the problem.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Reimplemented in Problem< OPE, VAR, PST >, and Calphad_Problem< CALPHAD, VAR, PST >.
Definition at line 364 of file ProblemBase.hpp.
get_convergence()
template<class VAR , class PST > std::vector< std::tuple< std::string, bool, double > > ProblemBase< VAR, PST >::get_convergence
Return for each variable, a tuple (string,string, boolean, double) where the boolean is the flag indicating if the criterion is reached or not, and the double is the criterion reached. The first string is the name of the problem, and the second the name of the variable.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Returns
std::vector<std::tuple<std::string, bool, double>>
Definition at line 464 of file ProblemBase.hpp.
get_name()
template<class VAR , class PST > std::string ProblemBase< VAR, PST >::get_name
Returns the name of the problem.
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Returns
std::string The name of the problem.
Definition at line 259 of file ProblemBase.hpp.
get_problem_variables()
template<class VAR , class PST > VAR ProblemBase< VAR, PST >::get_problem_variables
Return the variables associated with the problem.
Template Parameters
VAR Type representing the Variables.
PST Type representing the PostProcessing.
Returns
VAR The list of Variables of the problem.
Definition at line 271 of file ProblemBase.hpp.
initialize()
template<class VAR , class PST > void ProblemBase< VAR, PST >::initialize (const double & initial_time) virtual
Initialize the problem.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
initial_time The initial time of the simulation.
Reimplemented in Property_problem< PROPERTY, VAR, PST >, Problem< OPE, VAR, PST >, and Calphad_Problem< CALPHAD, VAR, PST >.
Definition at line 314 of file ProblemBase.hpp.
post_execute()
template<class VAR , class PST > void ProblemBase< VAR, PST >::post_execute (const int & iter, const double & current_time, const double & current_time_step) virtual
Performs actions after the execute step.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
iter Current iteration number.
current_time Current simulation time.
current_time_step Current time-step.
Reimplemented in Problem< OPE, VAR, PST >.
Definition at line 285 of file ProblemBase.hpp.
post_processing()
template<class VAR , class PST > void ProblemBase< VAR, PST >::post_processing (const int & iter, const double & current_time, const double & current_time_step) virtual
Save variables of the problem (see save method for other actions)
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
iter Current iteration number.
current_time Current simulation time.
current_time_step Current time-step.
Reimplemented in Problem< OPE, VAR, PST >, and Calphad_Problem< CALPHAD, VAR, PST >.
Definition at line 378 of file ProblemBase.hpp.
Referenced by Calphad_Problem< CALPHAD, VAR, PST >::post_processing(), and Problem< OPE, VAR, PST >::post_processing().
save()
template<class VAR , class PST > void ProblemBase< VAR, PST >::save (const int & iter, const double & current_time)
Save variables.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Parameters
iter Current iteration number.
current_time Current simulation time.
Definition at line 449 of file ProblemBase.hpp.
update()
template<class VAR , class PST > void ProblemBase< VAR, PST >::update
Update the variables associated with the problem.
Template Parameters
VAR Type representing the problem Variables.
PST Type representing the post-processing.
Definition at line 295 of file ProblemBase.hpp.
Member Data Documentation
auxvariables_
template<class VAR , class PST > std::vector<VAR*> ProblemBase< VAR, PST >::auxvariables_ protected
Definition at line 56 of file ProblemBase.hpp.
Referenced by ProblemBase< VAR, PST >::ProblemBase().
convergence_
template<class VAR , class PST > std::shared_ptr<Convergence> ProblemBase< VAR, PST >::convergence_ protected
Definition at line 60 of file ProblemBase.hpp.
Referenced by ProblemBase< VAR, PST >::ProblemBase().
name_
template<class VAR , class PST > std::string ProblemBase< VAR, PST >::name_ {"Unnamed problem"} protected
Definition at line 54 of file ProblemBase.hpp.
pop_elem_
template<class VAR , class PST > const std::list<int> ProblemBase< VAR, PST >::pop_elem_ protected
Definition at line 58 of file ProblemBase.hpp.
Referenced by ProblemBase< VAR, PST >::ProblemBase().
pst_
template<class VAR , class PST > PST& ProblemBase< VAR, PST >::pst_ protected
Definition at line 57 of file ProblemBase.hpp.
unknown_
template<class VAR , class PST > std::vector<mfem::Vector> ProblemBase< VAR, PST >::unknown_ protected
Definition at line 59 of file ProblemBase.hpp.
var_convergence_
template<class VAR , class PST > std::vector<std::tuple<std::string, bool, double> > ProblemBase< VAR, PST >::var_convergence_ protected
Definition at line 61 of file ProblemBase.hpp.
variables_
template<class VAR , class PST > VAR& ProblemBase< VAR, PST >::variables_ protected
Definition at line 55 of file ProblemBase.hpp.
The documentation for this class was generated from the following file:
ProblemBase.hpp