SLOTH: SlothInfo Class Reference
SlothInfo Class Reference
Class used to print information depending on the level of verbosity.
#include <UtilsForData.hpp>
Static Public Member Functions
template<typename... Args>
static void debug (Args... args)
Print information on Debug mode.
template<typename... Args>
static void error (Args... args)
Print information on Error mode.
template<typename... Args>
static void print (Args... args)
Print information on Normal mode.
template<typename... Args>
static void verbose (Args... args)
Print information on Normal mode.
Detailed Description
Class used to print information depending on the level of verbosity.
Definition at line 231 of file UtilsForData.hpp.
Member Function Documentation
debug()
template<typename... Args> static void SlothInfo::debug (Args... args) inline static
Print information on Debug mode.
Template Parameters
Args
Parameters
args
Definition at line 240 of file UtilsForData.hpp.
References Debug, and verbosityLevel.
Referenced by SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), PrecondHypreDiagScale::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), PrecondDSmoother::create_solver(), KKS< T >::execute_linearization(), LSolver::LSolver(), NLSolver::NLSolver(), SetPrecondSolver::operator()(), SetPrecondNLSolver::operator()(), UtilsSolvers::print_prec_name(), UtilsSolvers::print_solver_name(), and SpatialDiscretization< T, DIM >::set_finite_element_space().
error()
template<typename... Args> static void SlothInfo::error (Args... args) inline static
Print information on Error mode.
Template Parameters
Args
Parameters
args
Definition at line 252 of file UtilsForData.hpp.
References Error, and verbosityLevel.
print()
template<typename... Args> static void SlothInfo::print (Args... args) inline static
Print information on Normal mode.
Template Parameters
Args
Parameters
args
Definition at line 278 of file UtilsForData.hpp.
References Normal, and verbosityLevel.
Referenced by KKS< T >::execute_linearization(), and Parameter::print().
verbose()
template<typename... Args> static void SlothInfo::verbose (Args... args) inline static
Print information on Normal mode.
Template Parameters
Args
Parameters
args
Definition at line 265 of file UtilsForData.hpp.
References Verbose, and verbosityLevel.
Referenced by Coupling< Args >::execute(), ProblemBase< VAR, PST >::execute(), Coupling< Args >::get_tree(), TimeDiscretization< Args >::get_tree(), specialized_spatial_constructor< T, 1 >::operator()(), specialized_spatial_constructor< T, 2 >::operator()(), and specialized_spatial_constructor< T, 3 >::operator()().
The documentation for this class was generated from the following file:
UtilsForData.hpp