SLOTH: CalphadInformedNeuralNetwork< T > Class Template Reference
CalphadInformedNeuralNetwork< T > Class Template Reference
Calphad calculation performed by neural network Dedicated to simulations with multicomponent inter-diffusion.
#include <CalphadInformedNeuralNetwork.hpp>
Public Member Functions
constexpr CalphadInformedNeuralNetwork (const Parameters &params)
Construct a new CalphadInformedNeuralNetwork::CalphadInformedNeuralNetwork object.
constexpr CalphadInformedNeuralNetwork (const Parameters &params, bool is_KKS)
Construct a new CalphadInformedNeuralNetwork::CalphadInformedNeuralNetwork object.
void execute (const int dt, const std::set< int > &list_nodes, const std::vector< T > &aux_gf, const std::vector< std::tuple< std::string, std::string >> &chemical_system, std::optional< std::vector< std::tuple< std::string, std::string, double >>> status_phase=std::nullopt) override
Perform equilibrium calculations in a specific phase.
void finalize () override
Finalization actions (free memory)
void get_parameters () override
Get the parameters associated with the CalphadInformedNeuralNetwork object.
void initialize (const std::vector< std::tuple< std::string, std::string >> &sorted_chemical_system) override
Initialization of the thermodynamic calculation.
~CalphadInformedNeuralNetwork ()
Destroy the Binary Melting< T>:: Binary Melting object.
Public Member Functions inherited from CalphadBase< T >
CalphadBase (const Parameters &params)
Construct a new CalphadBase object.
CalphadBase (const Parameters &params, bool is_KKS)
Construct a new CalphadBase object.
const std::multimap< IterationKey, SpecializedValue > get_time_specialized () const
Return values calculated at a given iteration.
void global_execute (const int dt, const double time_step, const std::vector< T > &tp_gf, const std::vector< std::tuple< std::string, std::string >> &chemicalsystem, std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< T >>> &output_system, const std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> &previous_output_system, std::optional< const std::tuple< std::string, T, T >> phase_fields=std::nullopt, std::optional< const std::vector< T >> tp_gf_old=std::nullopt, std::optional< const std::vector< std::tuple< std::string, std::string, T, T >>> x_gf=std::nullopt, std::optional< const std::vector< std::tuple< std::string, T >>> coordinates=std::nullopt)
High-level method for managing equilibrium calculations.
virtual ~CalphadBase ()
Destroy the Calphad Base< T>:: Calphad Base object.
Additional Inherited Members
Public Attributes inherited from CalphadBase< T >
std::map< std::tuple< int, std::string >, double > chemical_potentials_
std::map< std::tuple< int, std::string >, double > diffusion_chemical_potentials_
std::map< std::tuple< int, std::string >, double > driving_forces_
std::map< std::tuple< int, std::string, std::string >, double > elem_mole_fraction_by_phase_
std::string element_removed_from_ic_
std::map< std::tuple< int, std::string, std::string >, double > energies_of_phases_
std::map< int, int > error_equilibrium_
std::map< std::tuple< int, std::string >, double > mole_fraction_of_phase_
std::map< std::tuple< int, std::string >, double > nucleus_
const Parameters & params_
std::multimap< IterationKey, SpecializedValue > time_specialized_
Time integral results.
Protected Member Functions inherited from CalphadBase< T >
void clear_containers ()
Clear containers used to store the results of equilibrium calculations.
void update_outputs (const int dt, const size_t nb_nodes, std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< T >>> &output_system, const std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> &previous_output_system)
Update the outputs on the basis of results stored in containers.
Protected Attributes inherited from CalphadBase< T >
std::shared_ptr< CalphadUtils< T > > CU_
std::map< int, double > heat_capacity_
std::shared_ptr< KKS< T > > KKS_
std::map< std::tuple< int, std::string, std::string >, double > mobilities_
std::map< std::tuple< int, std::string, std::string, int >, double > site_fraction_
Detailed Description
template<typename T>
class CalphadInformedNeuralNetwork< T >
Calphad calculation performed by neural network Dedicated to simulations with multicomponent inter-diffusion.
Template Parameters
T
Definition at line 56 of file CalphadInformedNeuralNetwork.hpp.
Constructor & Destructor Documentation
CalphadInformedNeuralNetwork() [1/2]
template<typename T > constexpr CalphadInformedNeuralNetwork< T >::CalphadInformedNeuralNetwork (const Parameters & params) explicit constexpr
Construct a new CalphadInformedNeuralNetwork::CalphadInformedNeuralNetwork object.
Parameters
params The parameter of the Calphad problem
Definition at line 299 of file CalphadInformedNeuralNetwork.hpp.
References CalphadInformedNeuralNetwork< T >::get_parameters().
CalphadInformedNeuralNetwork() [2/2]
template<typename T > constexpr CalphadInformedNeuralNetwork< T >::CalphadInformedNeuralNetwork (const Parameters & params, bool is_KKS) constexpr
Construct a new CalphadInformedNeuralNetwork::CalphadInformedNeuralNetwork object.
Parameters
params The parameter of the Calphad problem
is_KKS A boolean flag indicating whether to initialize KKS.
Definition at line 315 of file CalphadInformedNeuralNetwork.hpp.
References CalphadInformedNeuralNetwork< T >::get_parameters().
~CalphadInformedNeuralNetwork()
template<typename T > CalphadInformedNeuralNetwork< T >::~CalphadInformedNeuralNetwork
Destroy the Binary Melting< T>:: Binary Melting object.
Template Parameters
T
Definition at line 680 of file CalphadInformedNeuralNetwork.hpp.
Member Function Documentation
execute()
template<typename T > void CalphadInformedNeuralNetwork< T >::execute (const int dt, const std::set< int > & list_nodes, const std::vector< T > & tp_gf, const std::vector< std::tuple< std::string, std::string >> & chemical_system, std::optional< std::vector< std::tuple< std::string, std::string, double >>> status_phase = std::nullopt) override virtual
Perform equilibrium calculations in a specific phase.
Template Parameters
T
Parameters
dt The current iteration of the simulation
list_nodes The list of nodes where calculations are performed
tp_gf The thermodynamic condition for equilibrium calculations
chemical_system The targeted chemical system
status_phase A vector of phases with their status
Implements CalphadBase< T >.
Definition at line 426 of file CalphadInformedNeuralNetwork.hpp.
finalize()
template<typename T > void CalphadInformedNeuralNetwork< T >::finalize override virtual
Finalization actions (free memory)
Template Parameters
T
Implements CalphadBase< T >.
Definition at line 672 of file CalphadInformedNeuralNetwork.hpp.
get_parameters()
template<typename T > void CalphadInformedNeuralNetwork< T >::get_parameters override virtual
Get the parameters associated with the CalphadInformedNeuralNetwork object.
Template Parameters
T
Reimplemented from CalphadBase< T >.
Definition at line 140 of file CalphadInformedNeuralNetwork.hpp.
References check_file_existence(), and CalphadBase< T >::get_parameters().
Referenced by CalphadInformedNeuralNetwork< T >::CalphadInformedNeuralNetwork().
initialize()
template<typename T > void CalphadInformedNeuralNetwork< T >::initialize (const std::vector< std::tuple< std::string, std::string >> & sorted_chemical_system) override virtual
Initialization of the thermodynamic calculation.
Template Parameters
T
Implements CalphadBase< T >.
Definition at line 331 of file CalphadInformedNeuralNetwork.hpp.
The documentation for this class was generated from the following file:
CalphadInformedNeuralNetwork.hpp