SLOTH: Variable< T, DIM > Class Template Reference
Variable< T, DIM > Class Template Reference
#include <Variable.hpp>
Public Member Functions
std::vector< std::string > get_additional_variable_info () const
Return the additionnal information associated to variable.
std::shared_ptr< std::function< double(const mfem::Vector &, double)> > get_analytical_solution ()
return the function associated to the analytical solution
BoundaryConditions< T, DIM > * get_boundary_conditions ()
return the boundary condition object associated to the variable
mfem::ParFiniteElementSpace * get_fespace ()
Return the pointer towards the FiniteElementSpace.
mfem::ParGridFunction get_gf () const
return the gridfunction associated to the unknown
mfem::ParGridFunction get_igf () const
mfem::Vector get_last () const
Return the last term of the saved variables.
std::map< int, mfem::Vector > get_map_unknown ()
Return a map of unknows.
mfem::Vector get_second_to_last () const
Return the second-to-last term of the saved variables.
mfem::Vector get_unknown () const
return the unkown vector
std::string getVariableName () const
Get the name of the Variable.
template<class... Args>
void set_additional_information (Args &&... add_var_info)
Associate additional information to the variable.
void update (const mfem::Vector &unk)
update the GridFunction on the basis of its associated unknown vector
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name, const std::set< std::string > &attribute_names)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name, const std::set< std::string > &attribute_names, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const AnalyticalFunctions< DIM > &initial_condition_name, const std::set< std::string > &attribute_names, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value, const std::set< std::string > &attribute_names)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value, const std::set< std::string > &attribute_names, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const double &initial_condition_value, const std::set< std::string > &attribute_names, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function, const std::set< std::string > &attribute_names)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function, const std::set< std::string > &attribute_names, const AnalyticalFunctions< DIM > &analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const int &depth, const mfem::FunctionCoefficient &initial_condition_function, const std::set< std::string > &attribute_names, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
~Variable ()
Destroy the Variable:: Variable object.
Detailed Description
template<class T, int DIM>
class Variable< T, DIM >
Definition at line 45 of file Variable.hpp.
Constructor & Destructor Documentation
Variable() [1/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
Definition at line 211 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [2/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
analytical_solution_name
Definition at line 238 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [3/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
analytical_solution_function
Definition at line 269 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [4/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
Definition at line 297 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [5/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
analytical_solution_name
Definition at line 322 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [6/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
analytical_solution_function
Definition at line 352 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [7/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
Definition at line 378 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [8/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
analytical_solution_name
Definition at line 401 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [9/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
analytical_solution_function
Definition at line 430 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [10/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name, const std::set< std::string > & attribute_names)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
Definition at line 458 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [11/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name, const std::set< std::string > & attribute_names, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
analytical_solution_name
Definition at line 486 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [12/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const AnalyticalFunctions< DIM > & initial_condition_name, const std::set< std::string > & attribute_names, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_name
analytical_solution_function
Definition at line 521 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [13/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function, const std::set< std::string > & attribute_names)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
Definition at line 552 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [14/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function, const std::set< std::string > & attribute_names, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
analytical_solution_name
Definition at line 579 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [15/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const mfem::FunctionCoefficient & initial_condition_function, const std::set< std::string > & attribute_names, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_function
analytical_solution_function
Definition at line 612 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [16/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value, const std::set< std::string > & attribute_names)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
Definition at line 641 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [17/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value, const std::set< std::string > & attribute_names, const AnalyticalFunctions< DIM > & analytical_solution_name)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
analytical_solution_name
Definition at line 667 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
Variable() [18/18]
template<class T , int DIM> Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const int & depth, const double & initial_condition_value, const std::set< std::string > & attribute_names, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
depth
initial_condition_value
analytical_solution_function
Definition at line 698 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
~Variable()
template<class T , int DIM> Variable< T, DIM >::~Variable
Destroy the Variable:: Variable object.
Definition at line 1044 of file Variable.hpp.
Member Function Documentation
get_additional_variable_info()
template<class T , int DIM> std::vector< std::string > Variable< T, DIM >::get_additional_variable_info
Return the additionnal information associated to variable.
Template Parameters
T
DIM
Returns
std::vector<std::string>
Definition at line 918 of file Variable.hpp.
get_analytical_solution()
template<class T , int DIM> std::shared_ptr< std::function< double(const mfem::Vector &, double)> > Variable< T, DIM >::get_analytical_solution
return the function associated to the analytical solution
Template Parameters
T
DIM
Returns
std::function<double(const mfem::Vector&, double)>
Definition at line 953 of file Variable.hpp.
get_boundary_conditions()
template<class T , int DIM> BoundaryConditions< T, DIM > * Variable< T, DIM >::get_boundary_conditions
return the boundary condition object associated to the variable
Template Parameters
T
DIM
Returns
BoundaryConditions<T, DIM>
Definition at line 965 of file Variable.hpp.
get_fespace()
template<class T , int DIM> mfem::ParFiniteElementSpace * Variable< T, DIM >::get_fespace
Return the pointer towards the FiniteElementSpace.
Definition at line 1014 of file Variable.hpp.
get_gf()
template<class T , int DIM> mfem::ParGridFunction Variable< T, DIM >::get_gf
return the gridfunction associated to the unknown
Returns
mfem::ParGridFunction
Definition at line 940 of file Variable.hpp.
get_igf()
template<class T , int DIM> mfem::ParGridFunction Variable< T, DIM >::get_igf () const
get_last()
template<class T , int DIM> mfem::Vector Variable< T, DIM >::get_last
Return the last term of the saved variables.
Template Parameters
T
DIM
Returns
mfem::Vector
Definition at line 864 of file Variable.hpp.
get_map_unknown()
template<class T , int DIM> std::map< int, mfem::Vector > Variable< T, DIM >::get_map_unknown
Return a map of unknows.
Template Parameters
T
DIM
Returns
std::map<int, mfem::Vector>
Definition at line 930 of file Variable.hpp.
get_second_to_last()
template<class T , int DIM> mfem::Vector Variable< T, DIM >::get_second_to_last
Return the second-to-last term of the saved variables.
Template Parameters
T
DIM
Returns
mfem::Vector
Definition at line 852 of file Variable.hpp.
get_unknown()
template<class T , int DIM> mfem::Vector Variable< T, DIM >::get_unknown
return the unkown vector
Returns
mfem::Vector
Definition at line 906 of file Variable.hpp.
getVariableName()
template<class T , int DIM> std::string Variable< T, DIM >::getVariableName
Get the name of the Variable.
Returns
std::string name of the variable
Definition at line 975 of file Variable.hpp.
set_additional_information()
template<class T , int DIM> template<class... Args> void Variable< T, DIM >::set_additional_information (Args &&... add_var_info)
Associate additional information to the variable.
Template Parameters
T
DIM
Args
Parameters
add_var_info
Definition at line 726 of file Variable.hpp.
update()
template<class T , int DIM> void Variable< T, DIM >::update (const mfem::Vector & unk)
update the GridFunction on the basis of its associated unknown vector
Definition at line 873 of file Variable.hpp.
The documentation for this class was generated from the following file:
Variable.hpp