SLOTH: PropertyBase Class Reference
PropertyBase Class Reference abstract
#include <PropertyBase.hpp>
Public Member Functions
void compute (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> &output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system)
Compute the variables (properties) as functions of auxiliary variables.
PropertyBase (const Parameters &params)
Construct a new PropertyBase::PropertyBase object.
virtual ~PropertyBase ()=default
Protected Member Functions
virtual void check_variables_consistency (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> &output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system)=0
Check the consistency of the inputs and outputs of the property problem.
virtual void get_property (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> &output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system)=0
Get the values of the property.
Protected Attributes
bool is_checked_ {false}
const Parameters & params_
Detailed Description
Definition at line 46 of file PropertyBase.hpp.
Constructor & Destructor Documentation
PropertyBase()
PropertyBase::PropertyBase (const Parameters & params) explicit
Construct a new PropertyBase::PropertyBase object.
Definition at line 93 of file PropertyBase.hpp.
~PropertyBase()
virtual PropertyBase::~PropertyBase () virtual default
Member Function Documentation
check_variables_consistency()
virtual void PropertyBase::check_variables_consistency (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> & output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system) protected pure virtual
Check the consistency of the inputs and outputs of the property problem.
Parameters
output_system The outputs property problem (primary variables).
input_system The inputs of the property problem (auxiliary variables).
Implemented in InterDiffusionCoefficient.
Referenced by compute().
compute()
void PropertyBase::compute (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> & output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system)
Compute the variables (properties) as functions of auxiliary variables.
Parameters
output_system The outputs property problem (primary variables).
input_system The inputs of the property problem (auxiliary variables).
Definition at line 101 of file PropertyBase.hpp.
References check_variables_consistency(), get_property(), and is_checked_.
get_property()
virtual void PropertyBase::get_property (std::vector< std::tuple< std::vector< std::string >, std::reference_wrapper< mfem::Vector >>> & output_system, std::vector< std::tuple< std::vector< std::string >, mfem::Vector >> input_system) protected pure virtual
Get the values of the property.
The values of the property are stored in the outputs (primary variables of the property problem). They are calculated from the inputs (auxiliary variables of the property problem).
Parameters
output_system The outputs property problem (primary variables).
input_system The inputs of the property problem (auxiliary variables).
Implemented in InterDiffusionCoefficient.
Referenced by compute().
Member Data Documentation
is_checked_
bool PropertyBase::is_checked_ {false} protected
Definition at line 52 of file PropertyBase.hpp.
Referenced by compute().
params_
const Parameters& PropertyBase::params_ protected
Definition at line 49 of file PropertyBase.hpp.
Referenced by InterDiffusionCoefficient::InterDiffusionCoefficient().
The documentation for this class was generated from the following file:
PropertyBase.hpp