SLOTH: Parameter Class Reference
Parameter Class Reference
#include <Parameter.hpp>
Public Member Functions
std::string get_description () const
Return the description of the parameter.
std::string get_name () const
Return the name of the parameter.
auto get_value () const -> param_type
Return the value of the paramter.
Parameter (const std::string &name, param_type value)
Parameter (const std::string &name, param_type value, const std::string &description)
void print () const
Print the value of the parameter.
~Parameter ()
Detailed Description
Definition at line 40 of file Parameter.hpp.
Constructor & Destructor Documentation
Parameter() [1/2]
Parameter::Parameter (const std::string & name, param_type value) inline
Definition at line 47 of file Parameter.hpp.
Parameter() [2/2]
Parameter::Parameter (const std::string & name, param_type value, const std::string & description) inline
Definition at line 50 of file Parameter.hpp.
~Parameter()
Parameter::~Parameter () inline
Definition at line 62 of file Parameter.hpp.
Member Function Documentation
get_description()
std::string Parameter::get_description () const
Return the description of the parameter.
Returns
std::string
Definition at line 170 of file Parameter.hpp.
get_name()
std::string Parameter::get_name () const
Return the name of the parameter.
Returns
std::string
Definition at line 163 of file Parameter.hpp.
Referenced by print().
get_value()
auto Parameter::get_value () const -> param_type
Return the value of the paramter.
Returns
std::variant<int, double, std::string>
Definition at line 139 of file Parameter.hpp.
Referenced by Parameters::get_param_value(), Parameters::get_param_value_or_default(), and print().
print()
void Parameter::print () const
Print the value of the parameter.
Definition at line 69 of file Parameter.hpp.
References get_name(), get_value(), and SlothInfo::print().
The documentation for this class was generated from the following file:
Parameter.hpp