SLOTH: OperatorBase< T, DIM, NLFI, LHS_NLFI > Class Template Reference
OperatorBase< T, DIM, NLFI, LHS_NLFI > Class Template Reference abstract
Base class for building Steady and TimeDependent PhaseFieldOperators.
#include <OperatorBase.hpp>
Public Member Functions
void clear_iso_time_specialized ()
Clear time_iso_specialized_ container.
void clear_time_specialized ()
Clear time_specialized_ container.
virtual void ComputeEnergies (const int &it, const double &dt, const double &t, const std::vector< mfem::Vector > &u)=0
void ComputeError (const int &it, const double &t, const double &dt, const int id_var, const std::string &name, const mfem::Vector &u, std::function< double(const mfem::Vector &, double)> solution_func)
Compute L2 error.
void ComputeIntegral (const int &it, const double &t, const double &dt, const int id_var, const std::string &name, const mfem::Vector &u, const double lower_bound, const double upper_bound)
Compute integrals of a variable over the domain.
void ComputeIsoVal (const int &it, const double &t, const double &dt, const int var_id, const std::string &var_name, const mfem::Vector &u, const double &iso_value)
Compute the position of an isovalue.
std::string get_description ()
virtual void get_parameters ()=0
void get_source_term (const int id_block, const std::function< double(const mfem::Vector &, double)> &src_func, mfem::Vector &source_term, mfem::ParLinearForm *RHHS) const
Get the source term by equation of the PDEs.
const std::map< std::string, std::multimap< IterationKey, SpecializedValue > > get_time_iso_specialized () const
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
const std::multimap< IterationKey, SpecializedValue > get_time_specialized () const
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
virtual void initialize (const double &initial_time, Variables< T, DIM > &vars, std::vector< Variables< T, DIM > * > auxvars)
Initialization stage (call by imeDiscretization<PST, OPE, VAR>::initialize())
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials)
Construct a new OperatorBase object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params)
Construct a new OperatorBase object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters &params, const std::vector< AnalyticalFunctions< DIM >> &source_term_name)
Construct a new Phase Field Operator Base< T, DIM, NLFI>:: Phase Field Operator Base object.
OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const std::vector< AnalyticalFunctions< DIM >> &source_term_name)
Construct a new OperatorBase object.
void overload_nl_solver (NLSolverType NLSOLVER)
Overload the nonlinear algorithm.
void overload_nl_solver (NLSolverType NLSOLVER, const Parameters &nl_params)
Overload Parameters associated with nonlinear algorithm.
void overload_preconditioner (VSolverType PRECOND)
Overload the preconditioner used by the solver in the NL algorithm.
void overload_preconditioner (VSolverType PRECOND, const Parameters &p_params)
Overload the parameters of the preconditioner used by the solver in the NL algorithm.
void overload_solver (VSolverType SOLVER)
Overload the default linear solver used for the LHS.
void overload_solver (VSolverType SOLVER, const Parameters &s_params)
Overload the parameter for the linear solver used for the LHS.
virtual void set_default_properties ()=0
virtual NLFI * set_nlfi_ptr (const double dt, const std::vector< mfem::Vector > &u)=0
virtual void SetConstantParameters (const double dt, const std::vector< mfem::Vector > &u_vect)=0
virtual void SetTransientParameters (const double dt, const std::vector< mfem::Vector > &u_vect)=0
virtual void solve (std::vector< std::unique_ptr< mfem::Vector >> &vect_unk, double &next_time, const double &current_time, double current_time_step, const int iter)=0
virtual ~OperatorBase ()
Destroy the Operator Base<T, DIM, NLFI>:: Operator Base object.
Protected Member Functions
void build_rhs_nonlinear_form (const double dt, const std::vector< mfem::Vector > &u)
Build the NonLinear Form Integrator associated with the RHS of the PDEs.
int compute_total_height (const std::vector< SpatialDiscretization< T, DIM > * > &spatials)
Return the total height (output=rows of Operator) of the PDE system.
int compute_total_width (const std::vector< SpatialDiscretization< T, DIM > * > &spatials)
Return the total width (input=column of Operator) of the PDE system.
void SetNewtonAlgorithm (mfem::Operator *oper)
Configure the Newton solver.
Protected Attributes
std::vector< Variables< T, DIM > * > auxvariables_
std::vector< BoundaryConditions< T, DIM > * > bcs_
Boundary conditions.
mfem::Array< int > block_trueOffsets_
double current_dt_
double current_time_
const Parameter default_p_ = Parameter("default parameter", false)
const Parameters default_params_ = Parameters(default_p_)
std::string description_ {"UNKNOWN OPERATOR"}
std::vector< mfem::Array< int > > ess_tdof_list_
mfem::Array< mfem::ParFiniteElementSpace * > fes_
Finite Element Space and BCs.
int height_
std::shared_ptr< mfem::NewtonSolver > newton_solver_
NLFI * nlfi_ptr_
const Parameters & params_
mfem::ParBlockNonlinearForm * RHS
Right-Hand-Side.
NLSolver * rhs_solver_
std::vector< std::function< double(const mfem::Vector &, double)> > src_func_
std::map< std::string, std::multimap< IterationKey, SpecializedValue > > time_iso_specialized_
std::multimap< IterationKey, SpecializedValue > time_specialized_
Time integral results.
mfem::Vector z
Detailed Description
template<class T, int DIM, class NLFI, class LHS_NLFI>
class OperatorBase< T, DIM, NLFI, LHS_NLFI >
Base class for building Steady and TimeDependent PhaseFieldOperators.
Template Parameters
T
DIM
NLFI
Definition at line 59 of file OperatorBase.hpp.
Constructor & Destructor Documentation
OperatorBase() [1/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > OperatorBase< T, DIM, NLFI, LHS_NLFI >::OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials) explicit
Construct a new OperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
Definition at line 220 of file OperatorBase.hpp.
OperatorBase() [2/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > OperatorBase< T, DIM, NLFI, LHS_NLFI >::OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const std::vector< AnalyticalFunctions< DIM >> & source_term_name)
Construct a new OperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
source_term_name
Definition at line 256 of file OperatorBase.hpp.
OperatorBase() [3/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > OperatorBase< T, DIM, NLFI, LHS_NLFI >::OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters & params)
Construct a new OperatorBase object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
params
Definition at line 297 of file OperatorBase.hpp.
OperatorBase() [4/4]
template<class T , int DIM, class NLFI , class LHS_NLFI > OperatorBase< T, DIM, NLFI, LHS_NLFI >::OperatorBase (std::vector< SpatialDiscretization< T, DIM > * > spatials, const Parameters & params, const std::vector< AnalyticalFunctions< DIM >> & source_term_name)
Construct a new Phase Field Operator Base< T, DIM, NLFI>:: Phase Field Operator Base object.
Template Parameters
T
DIM
NLFI
Parameters
spatial
params
vars
auxvars
source_term_name
Definition at line 337 of file OperatorBase.hpp.
~OperatorBase()
template<class T , int DIM, class NLFI , class LHS_NLFI > OperatorBase< T, DIM, NLFI, LHS_NLFI >::~OperatorBase virtual
Destroy the Operator Base<T, DIM, NLFI>:: Operator Base object.
Template Parameters
T
DIM
NLFI
Definition at line 859 of file OperatorBase.hpp.
Member Function Documentation
build_rhs_nonlinear_form()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::build_rhs_nonlinear_form (const double dt, const std::vector< mfem::Vector > & u_vect) protected
Build the NonLinear Form Integrator associated with the RHS of the PDEs.
Template Parameters
T
DIM
NLFI
Parameters
dt
u
Definition at line 416 of file OperatorBase.hpp.
clear_iso_time_specialized()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::clear_iso_time_specialized
Clear time_iso_specialized_ container.
Template Parameters
T
Definition at line 708 of file OperatorBase.hpp.
clear_time_specialized()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::clear_time_specialized
Clear time_specialized_ container.
Template Parameters
T
Definition at line 733 of file OperatorBase.hpp.
compute_total_height()
template<class T , int DIM, class NLFI , class LHS_NLFI > int OperatorBase< T, DIM, NLFI, LHS_NLFI >::compute_total_height (const std::vector< SpatialDiscretization< T, DIM > * > & spatials) protected
Return the total height (output=rows of Operator) of the PDE system.
Template Parameters
T
DIM
NLFI
Parameters
spatials
Returns
int
Definition at line 181 of file OperatorBase.hpp.
compute_total_width()
template<class T , int DIM, class NLFI , class LHS_NLFI > int OperatorBase< T, DIM, NLFI, LHS_NLFI >::compute_total_width (const std::vector< SpatialDiscretization< T, DIM > * > & spatials) protected
Return the total width (input=column of Operator) of the PDE system.
Template Parameters
T
DIM
NLFI
LHS_NLFI
Parameters
spatials
Returns
int
Definition at line 201 of file OperatorBase.hpp.
ComputeEnergies()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::ComputeEnergies (const int & it, const double & dt, const double & t, const std::vector< mfem::Vector > & u) pure virtual
Implemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, PhaseFieldOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >.
ComputeError()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::ComputeError (const int & it, const double & t, const double & dt, const int id_var, const std::string & name, const mfem::Vector & u, std::function< double(const mfem::Vector &, double)> solution_func)
Compute L2 error.
Template Parameters
T
DIM
NLFI
LHS_NLFI
Parameters
it
t
dt
id_var
name
u
solution_func
Definition at line 465 of file OperatorBase.hpp.
ComputeIntegral()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::ComputeIntegral (const int & it, const double & t, const double & dt, const int id_var, const std::string & name, const mfem::Vector & u, const double lower_bound, const double upper_bound)
Compute integrals of a variable over the domain.
Template Parameters
T
DIM
NLFI
LHS_NLFI
Parameters
it
t
dt
id_var
name
u
integral_threshold
Definition at line 520 of file OperatorBase.hpp.
ComputeIsoVal()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::ComputeIsoVal (const int & it, const double & t, const double & dt, const int var_id, const std::string & var_name, const mfem::Vector & u, const double & iso_value)
Compute the position of an isovalue.
Parameters
it current iteration
t current time
dt current timestep
u unknown vector
iso_value value of the solution
Definition at line 591 of file OperatorBase.hpp.
get_description()
template<class T , int DIM, class NLFI , class LHS_NLFI > std::string OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_description () inline
Definition at line 139 of file OperatorBase.hpp.
References OperatorBase< T, DIM, NLFI, LHS_NLFI >::description_.
get_parameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_parameters () pure virtual
Implemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, PhaseFieldOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >.
get_source_term()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_source_term (const int id_block, const std::function< double(const mfem::Vector &, double)> & src_func, mfem::Vector & source_term, mfem::ParLinearForm * RHSS) const
Get the source term by equation of the PDEs.
Template Parameters
T
DIM
NLFI
Definition at line 672 of file OperatorBase.hpp.
get_time_iso_specialized()
template<class T , int DIM, class NLFI , class LHS_NLFI > const std::map< std::string, std::multimap< IterationKey, SpecializedValue > > OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_time_iso_specialized
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
Template Parameters
T
DIM
NLFI
Returns
const std::map<std::tuple<int, double, double>, double>
Definition at line 698 of file OperatorBase.hpp.
get_time_specialized()
template<class T , int DIM, class NLFI , class LHS_NLFI > const std::multimap< IterationKey, SpecializedValue > OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_time_specialized
Get a of a multimap of integral values calculated at a given iteration (see computeEnergies and computeError)
Template Parameters
T
DIM
NLFI
Returns
const std::map<std::tuple<int, double, double>, double>
Definition at line 723 of file OperatorBase.hpp.
initialize()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::initialize (const double & initial_time, Variables< T, DIM > & vars, std::vector< Variables< T, DIM > * > auxvars) virtual
Initialization stage (call by imeDiscretization<PST, OPE, VAR>::initialize())
Template Parameters
T
DIM
NLFI
Parameters
initial_time
vars
Reimplemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, and SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >.
Definition at line 379 of file OperatorBase.hpp.
References Variables< T, DIM >::get_variables_number(), and Variables< T, DIM >::getIVariable().
Referenced by SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::initialize(), and TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >::initialize().
overload_nl_solver() [1/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver (NLSolverType NLSOLVER)
Overload the nonlinear algorithm.
Remarks
NewtonSolver is the only one implemented
Template Parameters
T
DIM
NLFI
Parameters
NLSOLVER
Definition at line 770 of file OperatorBase.hpp.
Referenced by SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >::SteadyOperatorBase().
overload_nl_solver() [2/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_nl_solver (NLSolverType NLSOLVER, const Parameters & nl_params)
Overload Parameters associated with nonlinear algorithm.
Template Parameters
T
DIM
NLFI
Parameters
NLSOLVER
nl_params
Definition at line 784 of file OperatorBase.hpp.
overload_preconditioner() [1/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_preconditioner (VSolverType PRECOND)
Overload the preconditioner used by the solver in the NL algorithm.
Template Parameters
T
DIM
NLFI
Parameters
PRECOND
Definition at line 831 of file OperatorBase.hpp.
overload_preconditioner() [2/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_preconditioner (VSolverType PRECOND, const Parameters & p_params)
Overload the parameters of the preconditioner used by the solver in the NL algorithm.
Template Parameters
T
DIM
NLFI
Parameters
PRECOND
p_params
Definition at line 845 of file OperatorBase.hpp.
overload_solver() [1/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_solver (VSolverType SOLVER)
Overload the default linear solver used for the LHS.
Remarks
only used for explicit time-scheme
Template Parameters
T
DIM
NLFI
Parameters
SOLVER
s_params
Definition at line 801 of file OperatorBase.hpp.
overload_solver() [2/2]
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::overload_solver (VSolverType SOLVER, const Parameters & s_params)
Overload the parameter for the linear solver used for the LHS.
Remarks
only used for explicit time-scheme
Template Parameters
T
DIM
NLFI
Parameters
SOLVER
s_params
Definition at line 816 of file OperatorBase.hpp.
set_default_properties()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::set_default_properties () pure virtual
Implemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, PhaseFieldOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, PhaseFieldOperator< T, DIM, NLFI, LHS_NLFI >, SteadyPhaseFieldOperator< T, DIM, NLFI, LHS_NLFI >, HeatOperator< T, DIM, NLFI, LHS_NLFI, RHO, CP >, SteadyHeatOperator< T, DIM, NLFI, LHS_NLFI >, DiffusionOperator< T, DIM, NLFI, DENS, LHS_NLFI >, and SteadyDiffusionOperator< T, DIM, NLFI, LHS_NLFI >.
set_nlfi_ptr()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual NLFI* OperatorBase< T, DIM, NLFI, LHS_NLFI >::set_nlfi_ptr (const double dt, const std::vector< mfem::Vector > & u) pure virtual
Implemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, PhaseFieldOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, PhaseFieldOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, HeatOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, HeatOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >, DiffusionOperatorBase< T, DIM, NLFI, mfem::BlockNonlinearFormIntegrator, SteadyOperatorBase >, and DiffusionOperatorBase< T, DIM, NLFI, LHS_NLFI, TransientOperatorBase >.
SetConstantParameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::SetConstantParameters (const double dt, const std::vector< mfem::Vector > & u_vect) pure virtual
Implemented in TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >, and SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >.
SetNewtonAlgorithm()
template<class T , int DIM, class NLFI , class LHS_NLFI > void OperatorBase< T, DIM, NLFI, LHS_NLFI >::SetNewtonAlgorithm (mfem::Operator * oper) protected
Configure the Newton solver.
Template Parameters
T
DIM
NLFI
Parameters
oper
Definition at line 437 of file OperatorBase.hpp.
References NLSolver::get_nl_solver().
SetTransientParameters()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::SetTransientParameters (const double dt, const std::vector< mfem::Vector > & u_vect) pure virtual
Implemented in SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, and TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >.
solve()
template<class T , int DIM, class NLFI , class LHS_NLFI > virtual void OperatorBase< T, DIM, NLFI, LHS_NLFI >::solve (std::vector< std::unique_ptr< mfem::Vector >> & vect_unk, double & next_time, const double & current_time, double current_time_step, const int iter) pure virtual
Implemented in SteadyOperatorBase< T, DIM, NLFI, LHS_NLFI >, and TransientOperatorBase< T, DIM, NLFI, LHS_NLFI >.
Member Data Documentation
auxvariables_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::vector<Variables<T, DIM>*> OperatorBase< T, DIM, NLFI, LHS_NLFI >::auxvariables_ protected
Definition at line 72 of file OperatorBase.hpp.
bcs_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::vector<BoundaryConditions<T, DIM>*> OperatorBase< T, DIM, NLFI, LHS_NLFI >::bcs_ protected
Boundary conditions.
Definition at line 92 of file OperatorBase.hpp.
block_trueOffsets_
template<class T , int DIM, class NLFI , class LHS_NLFI > mfem::Array<int> OperatorBase< T, DIM, NLFI, LHS_NLFI >::block_trueOffsets_ protected
Definition at line 83 of file OperatorBase.hpp.
current_dt_
template<class T , int DIM, class NLFI , class LHS_NLFI > double OperatorBase< T, DIM, NLFI, LHS_NLFI >::current_dt_ protected
Definition at line 96 of file OperatorBase.hpp.
current_time_
template<class T , int DIM, class NLFI , class LHS_NLFI > double OperatorBase< T, DIM, NLFI, LHS_NLFI >::current_time_ protected
Definition at line 97 of file OperatorBase.hpp.
default_p_
template<class T , int DIM, class NLFI , class LHS_NLFI > const Parameter OperatorBase< T, DIM, NLFI, LHS_NLFI >::default_p_ = Parameter("default parameter", false) protected
Definition at line 74 of file OperatorBase.hpp.
default_params_
template<class T , int DIM, class NLFI , class LHS_NLFI > const Parameters OperatorBase< T, DIM, NLFI, LHS_NLFI >::default_params_ = Parameters(default_p_) protected
Definition at line 75 of file OperatorBase.hpp.
description_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::string OperatorBase< T, DIM, NLFI, LHS_NLFI >::description_ {"UNKNOWN OPERATOR"} protected
Definition at line 73 of file OperatorBase.hpp.
Referenced by OperatorBase< T, DIM, NLFI, LHS_NLFI >::get_description().
ess_tdof_list_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::vector<mfem::Array<int> > OperatorBase< T, DIM, NLFI, LHS_NLFI >::ess_tdof_list_ protected
Definition at line 82 of file OperatorBase.hpp.
fes_
template<class T , int DIM, class NLFI , class LHS_NLFI > mfem::Array<mfem::ParFiniteElementSpace*> OperatorBase< T, DIM, NLFI, LHS_NLFI >::fes_ protected
Finite Element Space and BCs.
Definition at line 81 of file OperatorBase.hpp.
height_
template<class T , int DIM, class NLFI , class LHS_NLFI > int OperatorBase< T, DIM, NLFI, LHS_NLFI >::height_ protected
Definition at line 98 of file OperatorBase.hpp.
newton_solver_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::shared_ptr<mfem::NewtonSolver> OperatorBase< T, DIM, NLFI, LHS_NLFI >::newton_solver_ protected
Definition at line 89 of file OperatorBase.hpp.
nlfi_ptr_
template<class T , int DIM, class NLFI , class LHS_NLFI > NLFI* OperatorBase< T, DIM, NLFI, LHS_NLFI >::nlfi_ptr_ protected
Definition at line 100 of file OperatorBase.hpp.
params_
template<class T , int DIM, class NLFI , class LHS_NLFI > const Parameters& OperatorBase< T, DIM, NLFI, LHS_NLFI >::params_ protected
Definition at line 76 of file OperatorBase.hpp.
RHS
template<class T , int DIM, class NLFI , class LHS_NLFI > mfem::ParBlockNonlinearForm* OperatorBase< T, DIM, NLFI, LHS_NLFI >::RHS protected
Right-Hand-Side.
Definition at line 86 of file OperatorBase.hpp.
rhs_solver_
template<class T , int DIM, class NLFI , class LHS_NLFI > NLSolver* OperatorBase< T, DIM, NLFI, LHS_NLFI >::rhs_solver_ protected
Definition at line 88 of file OperatorBase.hpp.
src_func_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::vector<std::function<double(const mfem::Vector&, double)> > OperatorBase< T, DIM, NLFI, LHS_NLFI >::src_func_ protected
Definition at line 94 of file OperatorBase.hpp.
time_iso_specialized_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::map<std::string, std::multimap<IterationKey, SpecializedValue> > OperatorBase< T, DIM, NLFI, LHS_NLFI >::time_iso_specialized_ protected
Definition at line 79 of file OperatorBase.hpp.
time_specialized_
template<class T , int DIM, class NLFI , class LHS_NLFI > std::multimap<IterationKey, SpecializedValue> OperatorBase< T, DIM, NLFI, LHS_NLFI >::time_specialized_ protected
Time integral results.
Definition at line 78 of file OperatorBase.hpp.
z
template<class T , int DIM, class NLFI , class LHS_NLFI > mfem::Vector OperatorBase< T, DIM, NLFI, LHS_NLFI >::z mutable protected
Definition at line 99 of file OperatorBase.hpp.
The documentation for this class was generated from the following file:
OperatorBase.hpp