SLOTH: SolverGMRES Class Reference
SolverGMRES Class Reference
#include <ISolverBase.hpp>
Public Member Functions
std::shared_ptr< mfem::GMRESSolver > create_solver (IterativeSolverType SOLVER, const Parameters &params) override
SolverGMRES ()
~SolverGMRES ()
Public Member Functions inherited from SolverBase< mfem::GMRESSolver, IterativeSolverType >
std::string get_description ()
virtual ~SolverBase ()=default
Additional Inherited Members
Public Attributes inherited from SolverBase< mfem::GMRESSolver, IterativeSolverType >
std::string solver_description_
Detailed Description
Definition at line 160 of file ISolverBase.hpp.
Constructor & Destructor Documentation
SolverGMRES()
SolverGMRES::SolverGMRES () inline
Definition at line 162 of file ISolverBase.hpp.
~SolverGMRES()
SolverGMRES::~SolverGMRES () inline
Definition at line 166 of file ISolverBase.hpp.
Member Function Documentation
create_solver()
std::shared_ptr< mfem::GMRESSolver > SolverGMRES::create_solver (IterativeSolverType SOLVER, const Parameters & params) override virtual
Implements SolverBase< mfem::GMRESSolver, IterativeSolverType >.
Definition at line 169 of file ISolverBase.hpp.
References GMRESDefaultConstant::abs_tol, SlothInfo::debug(), SolverBase< mfem::GMRESSolver, IterativeSolverType >::get_description(), Parameters::get_param_value(), Parameters::get_param_value_or_default(), GMRESDefaultConstant::iter_max, NewtonDefaultConstant::iterative_mode, GMRESDefaultConstant::iterative_mode, NewtonDefaultConstant::print_level, GMRESDefaultConstant::print_level, GMRESDefaultConstant::rel_tol, and SolverBase< mfem::GMRESSolver, IterativeSolverType >::solver_description_.
Referenced by SlothSolver::get_value().
The documentation for this class was generated from the following file:
ISolverBase.hpp