SLOTH: NLSolver Class Reference
NLSolver Class Reference
#include <NLSolver.hpp>
Public Member Functions
std::shared_ptr< mfem::NewtonSolver > get_nl_solver ()
Return the Non Linear Solver.
NLSolver (NLSolverType NLSOLVER, const Parameters &nl_params, VSolverType SOLVER, const Parameters &s_params, mfem::Operator &ope)
Construct a new NLSolver::NLSolver object.
NLSolver (NLSolverType NLSOLVER, const Parameters &nl_params, VSolverType SOLVER, const Parameters &s_params, VSolverType PRECOND, const Parameters &p_params, mfem::Operator &ope)
Construct a new NLSolver::NLSolver object.
~NLSolver ()
Destroy the Solver::Solver object.
Detailed Description
Definition at line 41 of file NLSolver.hpp.
Constructor & Destructor Documentation
NLSolver() [1/2]
NLSolver::NLSolver (NLSolverType NLSOLVER, const Parameters & nl_params, VSolverType SOLVER, const Parameters & s_params, VSolverType PRECOND, const Parameters & p_params, mfem::Operator & ope)
Construct a new NLSolver::NLSolver object.
Parameters
NLSOLVER
nl_params
SOLVER
s_params
PRECOND
p_params
ope
Definition at line 75 of file NLSolver.hpp.
References SlothInfo::debug().
NLSolver() [2/2]
NLSolver::NLSolver (NLSolverType NLSOLVER, const Parameters & nl_params, VSolverType SOLVER, const Parameters & s_params, mfem::Operator & ope)
Construct a new NLSolver::NLSolver object.
Parameters
NLSOLVER
nl_params
SOLVER
s_params
ope
Definition at line 99 of file NLSolver.hpp.
References SlothInfo::debug().
~NLSolver()
NLSolver::~NLSolver ()
Destroy the Solver::Solver object.
Definition at line 123 of file NLSolver.hpp.
Member Function Documentation
get_nl_solver()
std::shared_ptr< mfem::NewtonSolver > NLSolver::get_nl_solver ()
Return the Non Linear Solver.
Returns
std::shared_ptr<mfem::NewtonSolver>
Definition at line 117 of file NLSolver.hpp.
Referenced by OperatorBase< T, DIM, NLFI, LHS_NLFI >::SetNewtonAlgorithm().
The documentation for this class was generated from the following file:
NLSolver.hpp