SLOTH: PrecondHypreILU Class Reference
PrecondHypreILU Class Reference
#include <HPrecondBase.hpp>
Public Member Functions
std::shared_ptr< mfem::HypreILU > create_solver (HyprePreconditionerType PRECOND, const Parameters &params) override
Create preconditioner based of the PreconditionerType and a list of Parameters.
PrecondHypreILU ()
~PrecondHypreILU ()
Public Member Functions inherited from SolverBase< mfem::HypreILU, HyprePreconditionerType >
std::string get_description ()
virtual ~SolverBase ()=default
Additional Inherited Members
Public Attributes inherited from SolverBase< mfem::HypreILU, HyprePreconditionerType >
std::string solver_description_
Detailed Description
Definition at line 37 of file HPrecondBase.hpp.
Constructor & Destructor Documentation
PrecondHypreILU()
PrecondHypreILU::PrecondHypreILU () inline
Definition at line 39 of file HPrecondBase.hpp.
~PrecondHypreILU()
PrecondHypreILU::~PrecondHypreILU () inline
Definition at line 43 of file HPrecondBase.hpp.
Member Function Documentation
create_solver()
std::shared_ptr< mfem::HypreILU > PrecondHypreILU::create_solver (HyprePreconditionerType PRECOND, const Parameters & params) override virtual
Create preconditioner based of the PreconditionerType and a list of Parameters.
Parameters
PRECOND
params
Returns
std::shared_ptr<mfem::Solver>
Implements SolverBase< mfem::HypreILU, HyprePreconditionerType >.
Definition at line 53 of file HPrecondBase.hpp.
References SlothInfo::debug(), SolverBase< mfem::HypreILU, HyprePreconditionerType >::get_description(), Parameters::get_param_value(), Parameters::get_param_value_or_default(), HYPRE_ILU_DefaultConstant::iter_max, NewtonDefaultConstant::print_level, HYPRE_ILU_DefaultConstant::print_level, HYPRE_ILU_DefaultConstant::reorder_type, SolverBase< mfem::HypreILU, HyprePreconditionerType >::solver_description_, HYPRE_PCG_DefaultConstant::tol, HYPRE_ILU_DefaultConstant::tol, DSMOOTHER_DefaultConstant::type, and HYPRE_ILU_DefaultConstant::type.
Referenced by SlothSolver::get_value().
The documentation for this class was generated from the following file:
HPrecondBase.hpp