SLOTH: SolverHypreFGMRES Class Reference
SolverHypreFGMRES Class Reference
#include <HSolverBase.hpp>
Public Member Functions
std::shared_ptr< mfem::HypreFGMRES > create_solver (HypreSolverType SOLVER, const Parameters &params) override
Create a iterative solver based of the SolverType and a list of Parameters.
SolverHypreFGMRES ()
Construct a new HSolverBase::HSolverBase object.
~SolverHypreFGMRES ()
Destroy the HSolverBase::HSolverBase object.
Public Member Functions inherited from SolverBase< mfem::HypreFGMRES, HypreSolverType >
std::string get_description ()
virtual ~SolverBase ()=default
Additional Inherited Members
Public Attributes inherited from SolverBase< mfem::HypreFGMRES, HypreSolverType >
std::string solver_description_
Detailed Description
Definition at line 146 of file HSolverBase.hpp.
Constructor & Destructor Documentation
SolverHypreFGMRES()
SolverHypreFGMRES::SolverHypreFGMRES ()
Construct a new HSolverBase::HSolverBase object.
Definition at line 159 of file HSolverBase.hpp.
~SolverHypreFGMRES()
SolverHypreFGMRES::~SolverHypreFGMRES ()
Destroy the HSolverBase::HSolverBase object.
Definition at line 196 of file HSolverBase.hpp.
Member Function Documentation
create_solver()
std::shared_ptr< mfem::HypreFGMRES > SolverHypreFGMRES::create_solver (HypreSolverType SOLVER, const Parameters & params) override virtual
Create a iterative solver based of the SolverType and a list of Parameters.
Parameters
SOLVER
params
Returns
std::shared_ptr<mfem::IterativeSolver>
Implements SolverBase< mfem::HypreFGMRES, HypreSolverType >.
Definition at line 168 of file HSolverBase.hpp.
References SlothInfo::debug(), SolverBase< mfem::HypreFGMRES, HypreSolverType >::get_description(), Parameters::get_param_value(), Parameters::get_param_value_or_default(), NewtonDefaultConstant::iter_max, HYPRE_FGMRES_DefaultConstant::iter_max, GMRESDefaultConstant::kdim, HYPRE_FGMRES_DefaultConstant::kdim, NewtonDefaultConstant::print_level, HYPRE_FGMRES_DefaultConstant::print_level, SolverBase< mfem::HypreFGMRES, HypreSolverType >::solver_description_, HYPRE_PCG_DefaultConstant::tol, and HYPRE_FGMRES_DefaultConstant::tol.
Referenced by SlothSolver::get_value().
The documentation for this class was generated from the following file:
HSolverBase.hpp