SLOTH: SolverUMFPACK Class Reference
SolverUMFPACK Class Reference
#include <DSolverBase.hpp>
Public Member Functions
std::shared_ptr< mfem::UMFPackSolver > create_solver (DirectSolverType SOLVER, const Parameters &params) override
Create a direct solver based of the SolverType and a list of Parameters.
SolverUMFPACK ()
Construct a new SolverUMFPACK::SolverUMFPACK object.
~SolverUMFPACK ()
Destroy the SolverUMFPACK::SolverUMFPACK object.
Public Member Functions inherited from SolverBase< mfem::UMFPackSolver, DirectSolverType >
std::string get_description ()
virtual ~SolverBase ()=default
Additional Inherited Members
Public Attributes inherited from SolverBase< mfem::UMFPackSolver, DirectSolverType >
std::string solver_description_
Detailed Description
Definition at line 36 of file DSolverBase.hpp.
Constructor & Destructor Documentation
SolverUMFPACK()
SolverUMFPACK::SolverUMFPACK ()
Construct a new SolverUMFPACK::SolverUMFPACK object.
Definition at line 49 of file DSolverBase.hpp.
~SolverUMFPACK()
SolverUMFPACK::~SolverUMFPACK ()
Destroy the SolverUMFPACK::SolverUMFPACK object.
Definition at line 76 of file DSolverBase.hpp.
Member Function Documentation
create_solver()
std::shared_ptr< mfem::UMFPackSolver > SolverUMFPACK::create_solver (DirectSolverType SOLVER, const Parameters & params) override virtual
Create a direct solver based of the SolverType and a list of Parameters.
Parameters
SOLVER
params
Returns
std::shared_ptr<mfem::Solver>
Implements SolverBase< mfem::UMFPackSolver, DirectSolverType >.
Definition at line 58 of file DSolverBase.hpp.
References SlothInfo::debug(), SolverBase< mfem::UMFPackSolver, DirectSolverType >::get_description(), Parameters::get_param_value(), Parameters::get_param_value_or_default(), NewtonDefaultConstant::print_level, UMFPACK_DefaultConstant::print_level, and SolverBase< mfem::UMFPackSolver, DirectSolverType >::solver_description_.
Referenced by SlothSolver::get_value().
The documentation for this class was generated from the following file:
DSolverBase.hpp