SLOTH: HeatNLFormIntegrator< VARS, SCHEME, COND_NAME > Class Template Reference
HeatNLFormIntegrator< VARS, SCHEME, COND_NAME > Class Template Reference
Class dedicated to the FV of the heat transfer equation.
#include <HeatNLFormIntegrator.hpp>
Public Member Functions
virtual void AssembleElementGrad (const mfem::Array< const mfem::FiniteElement * > &el, mfem::ElementTransformation &Tr, const mfem::Array< const mfem::Vector * > &elfun, const mfem::Array2D< mfem::DenseMatrix * > &elmat)
Jacobian part of the non linear problem.
virtual void AssembleElementVector (const mfem::Array< const mfem::FiniteElement * > &el, mfem::ElementTransformation &Tr, const mfem::Array< const mfem::Vector * > &elfun, const mfem::Array< mfem::Vector * > &elvect)
Residual part of the non linear problem.
std::unique_ptr< HomogeneousEnergyCoefficient< ThermodynamicsPotentials::LOG > > get_energy (std::vector< mfem::ParGridFunction * > gfu, const double diffu)
HeatNLFormIntegrator (const std::vector< mfem::ParGridFunction > &u_old, const Parameters &params, std::vector< VARS * > auxvars)
Construct a new HeatNLFormIntegrator<SCHEME, COEFFICIENT>::HeatNLFormIntegrator object.
~HeatNLFormIntegrator ()
Destroy the HeatNLFormIntegrator<SCHEME, COEFFICIENT>::HeatNLFormIntegrator.
Public Member Functions inherited from SlothNLFormIntegrator< VARS >
SlothNLFormIntegrator (const Parameters &params, std::vector< VARS * > auxvars)
Construct a new SlothNLFormIntegrator::SlothNLFormIntegrator object.
~SlothNLFormIntegrator ()
Destroy the SlothNLFormIntegrator::SlothNLFormIntegrator object.
Additional Inherited Members
Protected Member Functions inherited from SlothNLFormIntegrator< VARS >
std::vector< mfem::ParGridFunction > get_aux_gf ()
Return a vector of GridFunction associated with auxiliary variables.
std::vector< std::vector< std::string > > get_aux_infos ()
Return a vector of the additional information (vector of string) associated with auxiliary variables.
std::vector< mfem::Vector > get_aux_old_gf ()
Return a vector of GridFunction associated with auxiliary variables at the previous time-step.
Protected Attributes inherited from SlothNLFormIntegrator< VARS >
std::vector< VARS * > auxvariables_
const Parameters params_
Detailed Description
template<class VARS, CoefficientDiscretization SCHEME, Conductivity COND_NAME>
class HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >
Class dedicated to the FV of the heat transfer equation.
Template Parameters
SCHEME
COND_NAME
Definition at line 46 of file HeatNLFormIntegrator.hpp.
Constructor & Destructor Documentation
HeatNLFormIntegrator()
template<class VARS , CoefficientDiscretization SCHEME, Conductivity COND_NAME> HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >::HeatNLFormIntegrator (const std::vector< mfem::ParGridFunction > & u_old, const Parameters & params, std::vector< VARS * > auxvars)
Construct a new HeatNLFormIntegrator<SCHEME, COEFFICIENT>::HeatNLFormIntegrator object.
Template Parameters
SCHEME
COEFFICIENT
Parameters
u_old
alpha
kappa
Definition at line 150 of file HeatNLFormIntegrator.hpp.
References SlothNLFormIntegrator< VARS >::get_aux_gf(), SlothNLFormIntegrator< VARS >::get_aux_infos(), and SlothNLFormIntegrator< VARS >::get_aux_old_gf().
~HeatNLFormIntegrator()
template<class VARS , CoefficientDiscretization SCHEME, Conductivity COND_NAME> HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >::~HeatNLFormIntegrator
Destroy the HeatNLFormIntegrator<SCHEME, COEFFICIENT>::HeatNLFormIntegrator.
Template Parameters
SCHEME
COEFFICIENT
Definition at line 268 of file HeatNLFormIntegrator.hpp.
Member Function Documentation
AssembleElementGrad()
template<class VARS , CoefficientDiscretization SCHEME, Conductivity COND_NAME> void HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >::AssembleElementGrad (const mfem::Array< const mfem::FiniteElement * > & el, mfem::ElementTransformation & Tr, const mfem::Array< const mfem::Vector * > & elfun, const mfem::Array2D< mfem::DenseMatrix * > & elmat) virtual
Jacobian part of the non linear problem.
Parameters
el
Tr
elfun
elmat
Definition at line 213 of file HeatNLFormIntegrator.hpp.
AssembleElementVector()
template<class VARS , CoefficientDiscretization SCHEME, Conductivity COND_NAME> void HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >::AssembleElementVector (const mfem::Array< const mfem::FiniteElement * > & el, mfem::ElementTransformation & Tr, const mfem::Array< const mfem::Vector * > & elfun, const mfem::Array< mfem::Vector * > & elvect) virtual
Residual part of the non linear problem.
Parameters
el
Tr
elfun
elvect
Definition at line 169 of file HeatNLFormIntegrator.hpp.
get_energy()
template<class VARS , CoefficientDiscretization SCHEME, Conductivity COND_NAME> std::unique_ptr< HomogeneousEnergyCoefficient< ThermodynamicsPotentials::LOG > > HeatNLFormIntegrator< VARS, SCHEME, COND_NAME >::get_energy (std::vector< mfem::ParGridFunction * > gfu, const double diffu)
Definition at line 254 of file HeatNLFormIntegrator.hpp.
The documentation for this class was generated from the following file:
HeatNLFormIntegrator.hpp