SLOTH: UtilsSolvers Struct Reference
UtilsSolvers Struct Reference
Common methods for Linear and non Linear solvers.
#include <SlothSolver.hpp>
Static Public Member Functions
template<typename Prec >
static void print_prec_name (const Prec &)
Print the name of the Preconditioner.
template<typename Solv >
static void print_solver_name (const Solv &)
Print the name of the Solver.
template<typename Solv , typename Prec >
static void setter_hypre (Solv &solv, Prec &prec)
Set the Hypre Solver object.
template<typename Solv , typename Prec >
static void setter_mfem (Solv &solv, Prec &prec)
Set the mfem Solver object.
Detailed Description
Common methods for Linear and non Linear solvers.
Definition at line 85 of file SlothSolver.hpp.
Member Function Documentation
print_prec_name()
template<typename Prec > static void UtilsSolvers::print_prec_name (const Prec &) inline static
Print the name of the Preconditioner.
Template Parameters
Prec
Definition at line 148 of file SlothSolver.hpp.
References SlothInfo::debug().
Referenced by SetPrecondSolver::operator()(), and SetPrecondNLSolver::operator()().
print_solver_name()
template<typename Solv > static void UtilsSolvers::print_solver_name (const Solv &) inline static
Print the name of the Solver.
Template Parameters
Solv
Definition at line 120 of file SlothSolver.hpp.
References SlothInfo::debug().
Referenced by SetPrecondSolver::operator()(), and SetPrecondNLSolver::operator()().
setter_hypre()
template<typename Solv , typename Prec > static void UtilsSolvers::setter_hypre (Solv & solv, Prec & prec) inline static
Set the Hypre Solver object.
Template Parameters
Solv
Prec
Parameters
solv
prec
Definition at line 109 of file SlothSolver.hpp.
Referenced by SetPrecondSolver::operator()(), and SetPrecondNLSolver::operator()().
setter_mfem()
template<typename Solv , typename Prec > static void UtilsSolvers::setter_mfem (Solv & solv, Prec & prec) inline static
Set the mfem Solver object.
Template Parameters
Solv
Prec
Parameters
solv
prec
Definition at line 95 of file SlothSolver.hpp.
Referenced by SetPrecondSolver::operator()(), and SetPrecondNLSolver::operator()().
The documentation for this struct was generated from the following file:
SlothSolver.hpp