SLOTH: specialized_spatial_constructor< T, 2 > Struct Template Reference
specialized_spatial_constructor< T, 2 > Struct Template Reference
Specialization for dimension two.
#include <Spatial.hpp>
Public Member Functions
template<typename... Args>
void build_mesh (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, std::tuple< Args... > tup_args)
Build a two-dimensional mesh by using MFEM inline methods.
template<typename... Args>
void build_periodic_mesh (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, std::tuple< Args... > tup_args, std::vector< mfem::Vector > translations)
Build a periodic two-dimensional mesh by using MFEM inline methods.
template<typename... Args>
void operator() (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, const int &ref_level, const std::string &file, bool periodic_mesh)
operator() specialized for a mesh built from GMSH file
template<typename... Args>
void operator() (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, const int &ref_level, std::tuple< Args... > tup_args)
operator() specialized for a mesh built from MFEM methods
template<typename... Args>
void operator() (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, const int &ref_level, std::tuple< Args... > tup_args, std::vector< mfem::Vector > translations)
operator() specialized for a periodic mesh built from MFEM methods
Detailed Description
template<typename T>
struct specialized_spatial_constructor< T, 2 >
Specialization for dimension two.
Template Parameters
T
Definition at line 408 of file Spatial.hpp.
Member Function Documentation
build_mesh()
template<typename T > template<typename... Args> void specialized_spatial_constructor< T, 2 >::build_mesh (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, std::tuple< Args... > tup_args) inline
Build a two-dimensional mesh by using MFEM inline methods.
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
tup_args
Definition at line 512 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::dimension_, SpatialDiscretization< T, DIM >::fe_order_, Meshes::from(), Meshes::InlineSquareWithQuadrangles, Meshes::InlineSquareWithTriangles, SpatialDiscretization< T, DIM >::mesh_, and SpatialDiscretization< T, DIM >::mesh_max_bdr_attributes_.
build_periodic_mesh()
template<typename T > template<typename... Args> void specialized_spatial_constructor< T, 2 >::build_periodic_mesh (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, std::tuple< Args... > tup_args, std::vector< mfem::Vector > translations) inline
Build a periodic two-dimensional mesh by using MFEM inline methods.
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
tup_args
Definition at line 562 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::dimension_, SpatialDiscretization< T, DIM >::fe_order_, Meshes::from(), Meshes::InlineSquareWithQuadrangles, Meshes::InlineSquareWithTriangles, SpatialDiscretization< T, DIM >::mesh_, SpatialDiscretization< T, DIM >::mesh_max_bdr_attributes_, and HYPRE_PCG_DefaultConstant::tol.
operator()() [1/3]
template<typename T > template<typename... Args> void specialized_spatial_constructor< T, 2 >::operator() (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, const int & ref_level, const std::string & file, bool periodic_mesh) inline
operator() specialized for a mesh built from GMSH file
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
file
Definition at line 419 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::apply_uniform_refinement(), SpatialDiscretization< T, DIM >::dimension_, SpatialDiscretization< T, DIM >::fe_order_, Meshes::from(), Meshes::GMSH, SpatialDiscretization< T, DIM >::GMSHReaderSplitFiles(), SpatialDiscretization< T, DIM >::is_periodic_mesh_, SpatialDiscretization< T, DIM >::mesh_, SpatialDiscretization< T, DIM >::mesh_max_bdr_attributes_, SpatialDiscretization< T, DIM >::set_finite_element_space(), and SlothInfo::verbose().
operator()() [2/3]
template<typename T > template<typename... Args> void specialized_spatial_constructor< T, 2 >::operator() (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, const int & ref_level, std::tuple< Args... > tup_args) inline
operator() specialized for a mesh built from MFEM methods
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
tup_args
Definition at line 472 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::apply_uniform_refinement(), and SpatialDiscretization< T, DIM >::set_finite_element_space().
operator()() [3/3]
template<typename T > template<typename... Args> void specialized_spatial_constructor< T, 2 >::operator() (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, const int & ref_level, std::tuple< Args... > tup_args, std::vector< mfem::Vector > translations) inline
operator() specialized for a periodic mesh built from MFEM methods
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
tup_args
translations
Definition at line 491 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::apply_uniform_refinement(), SpatialDiscretization< T, DIM >::is_periodic_mesh_, and SpatialDiscretization< T, DIM >::set_finite_element_space().
The documentation for this struct was generated from the following file:
Spatial.hpp