SLOTH: Meshes Struct Reference
Meshes Struct Reference
#include <SpatialOptions.hpp>
Public Types
enum value {
InlineLineWithSegments , InlineSquareWithTriangles , InlineSquareWithQuadrangles , InlineSquareWithTetraedres ,
InlineSquareWithHexaedres , GMSH
}
Static Public Member Functions
static value from (const std::string &)
Detailed Description
Definition at line 36 of file SpatialOptions.hpp.
Member Enumeration Documentation
value
enum Meshes::value
Enumerator
InlineLineWithSegments
InlineSquareWithTriangles
InlineSquareWithQuadrangles
InlineSquareWithTetraedres
InlineSquareWithHexaedres
GMSH
Definition at line 37 of file SpatialOptions.hpp.
Member Function Documentation
from()
Meshes::value Meshes::from (const std::string & v) static
Definition at line 48 of file SpatialOptions.hpp.
References GMSH, InlineLineWithSegments, InlineSquareWithHexaedres, InlineSquareWithQuadrangles, InlineSquareWithTetraedres, and InlineSquareWithTriangles.
Referenced by specialized_spatial_constructor< T, 1 >::build_mesh(), specialized_spatial_constructor< T, 2 >::build_mesh(), specialized_spatial_constructor< T, 3 >::build_mesh(), specialized_spatial_constructor< T, 1 >::build_periodic_mesh(), specialized_spatial_constructor< T, 2 >::build_periodic_mesh(), specialized_spatial_constructor< T, 3 >::build_periodic_mesh(), specialized_spatial_constructor< T, 1 >::operator()(), specialized_spatial_constructor< T, 2 >::operator()(), and specialized_spatial_constructor< T, 3 >::operator()().
The documentation for this struct was generated from the following file:
SpatialOptions.hpp