SLOTH: SetPrecondSolver Struct Reference
SetPrecondSolver Struct Reference
Define a linear solver and its preconditioner (if required)
#include <SlothSolver.hpp>
Public Member Functions
template<typename Solv , typename Prec >
void operator() (Solv &&solv, Prec &&prec)
Main function.
Public Attributes
mfem::Operator & op
Detailed Description
Define a linear solver and its preconditioner (if required)
Definition at line 173 of file SlothSolver.hpp.
Member Function Documentation
operator()()
template<typename Solv , typename Prec > void SetPrecondSolver::operator() (Solv && solv, Prec && prec) inline
Main function.
Template Parameters
Solv
Prec
Parameters
solv
prec
Definition at line 186 of file SlothSolver.hpp.
References SlothInfo::debug(), UtilsSolvers::print_prec_name(), UtilsSolvers::print_solver_name(), UtilsSolvers::setter_hypre(), and UtilsSolvers::setter_mfem().
Member Data Documentation
op
mfem::Operator& SetPrecondSolver::op
Definition at line 175 of file SlothSolver.hpp.
The documentation for this struct was generated from the following file:
SlothSolver.hpp