SLOTH: UtilsForData.hpp File Reference
UtilsForData.hpp File Reference
Usefull methods for data.
#include <unistd.h>
#include <cctype>
#include <cstdio>
#include <algorithm>
#include <filesystem>
#include <functional>
#include <iostream>
#include <map>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "mfem.hpp"
Classes
class SlothInfo
Class used to print information depending on the level of verbosity.
Typedefs
using FType = std::function< double(const double &)>
using FuncType = std::function< double(const double &, const double &)>
using Map2String2Double = std::map< std::tuple< std::string, std::string >, std::tuple< double, double > >
using MapString2Double = std::map< std::string, std::tuple< double, double > >
using MapStringDouble = std::map< std::string, double >
using SpecializedValue = std::pair< std::string, double >
using triplet = std::tuple< std::string, double, std::string >
using vDouble = std::vector< double >
using vInt = std::vector< int >
using vString = std::vector< std::string >
using vtriplet = std::vector< triplet >
using vTuple2StringDouble = std::vector< std::tuple< std::string, std::string, double > >
using vTupleStringInt = std::vector< std::tuple< std::string, int > >
using vTupleStringString = std::vector< std::tuple< std::string, std::string > >
Enumerations
enum class Verbosity {
Quiet , Normal , Verbose , Debug ,
Error
}
Levels of verbosity.
Functions
static void check_file_existence (const std::string &file)
Check existence of a file.
template<typename Func , typename... Args>
static void external_call (Verbosity verbosity, Func func, Args &&... args)
Method used to capture the flux coming from an external method and print it depending on the verbosity level.
static void setVerbosity (Verbosity verbosity)
Set the level of verbosity.
static std::string toLowerCase (const std::string &str)
Put string in lowercase.
static std::string toUpperCase (const std::string &str)
Put string in uppercase.
static std::string trim (const std::string &str)
Trim leading and trailing whitespace.
Variables
static auto stringfindInVectorOfString
Search string in a vector of string.
static Verbosity verbosityLevel = Verbosity::Quiet
The current level of verbosity.
Detailed Description
Usefull methods for data.
Author
Clément Introïni (cleme.nosp@m.nt.i.nosp@m.ntroi.nosp@m.ni@c.nosp@m.ea.fr)
Version
0.1
Date
2025-09-05
Copyright CEA (C) 2025
This file is part of SLOTH.
SLOTH is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SLOTH is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file UtilsForData.hpp.
Typedef Documentation
FType
using FType = std::function<double(const double&)>
Definition at line 48 of file UtilsForData.hpp.
FuncType
using FuncType = std::function<double(const double&, const double&)>
Definition at line 47 of file UtilsForData.hpp.
Map2String2Double
using Map2String2Double = std::map<std::tuple<std::string, std::string>, std::tuple<double, double> >
Definition at line 57 of file UtilsForData.hpp.
MapString2Double
using MapString2Double = std::map<std::string, std::tuple<double, double> >
Definition at line 56 of file UtilsForData.hpp.
MapStringDouble
using MapStringDouble = std::map<std::string, double>
Definition at line 54 of file UtilsForData.hpp.
SpecializedValue
using SpecializedValue = std::pair<std::string, double>
Definition at line 59 of file UtilsForData.hpp.
triplet
using triplet = std::tuple<std::string, double, std::string>
Definition at line 61 of file UtilsForData.hpp.
vDouble
using vDouble = std::vector<double>
Definition at line 52 of file UtilsForData.hpp.
vInt
using vInt = std::vector<int>
Definition at line 53 of file UtilsForData.hpp.
vString
using vString = std::vector<std::string>
Definition at line 51 of file UtilsForData.hpp.
vtriplet
using vtriplet = std::vector<triplet>
Definition at line 62 of file UtilsForData.hpp.
vTuple2StringDouble
using vTuple2StringDouble = std::vector<std::tuple<std::string, std::string, double> >
Definition at line 55 of file UtilsForData.hpp.
vTupleStringInt
using vTupleStringInt = std::vector<std::tuple<std::string, int> >
Definition at line 49 of file UtilsForData.hpp.
vTupleStringString
using vTupleStringString = std::vector<std::tuple<std::string, std::string> >
Definition at line 50 of file UtilsForData.hpp.
Enumeration Type Documentation
Verbosity
enum Verbosity strong
Levels of verbosity.
Enumerator
Quiet
Normal
Verbose
Debug
Error
Definition at line 120 of file UtilsForData.hpp.
Function Documentation
check_file_existence()
static void check_file_existence (const std::string & file) static
Check existence of a file.
Parameters
file
Definition at line 218 of file UtilsForData.hpp.
Referenced by CalphadInformedNeuralNetwork< T >::get_parameters().
external_call()
template<typename Func , typename... Args> static void external_call (Verbosity verbosity, Func func, Args &&... args) static
Method used to capture the flux coming from an external method and print it depending on the verbosity level.
Template Parameters
Func
Args
Parameters
verbosity
func
args
Definition at line 170 of file UtilsForData.hpp.
References Verbose.
setVerbosity()
static void setVerbosity (Verbosity verbosity) static
Set the level of verbosity.
Parameters
verbosity
Definition at line 133 of file UtilsForData.hpp.
References verbosityLevel.
toLowerCase()
static std::string toLowerCase (const std::string & str) static
Put string in lowercase.
Parameters
str
Returns
std::string
Definition at line 90 of file UtilsForData.hpp.
Referenced by InterDiffusionCoefficient::check_variables_consistency().
toUpperCase()
static std::string toUpperCase (const std::string & str) static
Put string in uppercase.
Parameters
str
Returns
std::string
Definition at line 78 of file UtilsForData.hpp.
Referenced by InterDiffusionCoefficient::get_property(), and InterDiffusionCoefficient::InterDiffusionCoefficient().
trim()
static std::string trim (const std::string & str) static
Trim leading and trailing whitespace.
Parameters
str
Returns
std::string
Definition at line 102 of file UtilsForData.hpp.
Variable Documentation
stringfindInVectorOfString
auto stringfindInVectorOfString static
Initial value:
= [](const std::vector<std::string> v, const std::string w) {
  return find(v.begin(), v.end(), w) != v.end();
}
Search string in a vector of string.
Definition at line 68 of file UtilsForData.hpp.
verbosityLevel
Verbosity verbosityLevel = Verbosity::Quiet static
The current level of verbosity.
Definition at line 126 of file UtilsForData.hpp.
Referenced by SlothInfo::debug(), SlothInfo::error(), KKS< T >::execute_linearization(), SlothInfo::print(), setVerbosity(), and SlothInfo::verbose().