name: Build GitHub Pages

on:
  push:
    branches: [main]
 
jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python config
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build documentation
        run: |
            cmake -S doc -B build 
            cmake --build build --target doc -- VERBOSE=1
      - name: Deployment 
        run:  |
            cd build
            mkdocs gh-deploy --force
 